"""Tests for the DCGO-oracle keyword gate (tasks 3.1 / 3.2 / 3.3 / 3.4)."""

from tools.author_set.keyword_gate import (
    scan_bracket_tokens,
    triage_set,
    triage_set_from_artifacts,
)

# Lexicons / registries kept tiny + explicit for the unit tests.
TRAITS = {"sea animal", "machine"}
NAMES = {"greymon", "diaboromon"}
RUST = {"blocker", "rush", "piercing", "vortex"}
DCGO = RUST | {"appfusion", "link", "petrification"}  # DCGO has 3 the enum lacks


def triage(texts, **over):
    kw = dict(traits=TRAITS, card_names=NAMES, rust_keywords=RUST, dcgo_available=DCGO)
    kw.update(over)
    return triage_set(texts, **kw)


def test_positional_trait_rule_beats_lexicon_and_param():
    # "[Aqua] trait" is a trait even though 'aqua' is absent from the lexicon.
    rep = triage(["delete 1 of your [Aqua] trait Digimon"])
    assert "aqua" in rep.trait_hits
    assert "aqua" in rep.lexicon_misses  # surfaced as a suggested lexicon addition
    assert not rep.flag_for_human


def test_covered_keyword():
    rep = triage(["<Blocker> This Digimon can block."])
    assert "blocker" in rep.covered
    assert not rep.auto_ingest and not rep.flag_for_human


def test_fullwidth_angle_bracket_keyword_detected():
    # Real Digimon keyword tokens use FULLWIDTH angle brackets (＜＞ U+FF1C/FF1E),
    # not ASCII <>. The scanner must match them or it misses every keyword like
    # ＜Blocker＞ / ＜Rush＞ / ＜Ascension＞ (BT25 regression).
    rep = triage(["＜Blocker＞ (This Digimon can block in the blocker timing.)"])
    assert "blocker" in rep.covered


def test_auto_ingest_when_dcgo_has_it():
    rep = triage(["[App Fusion -4] ...", "When this Digimon has [Link]..."])
    assert "app fusion" in rep.auto_ingest
    assert "link" in rep.auto_ingest


def test_subsystem_keyword_routed_separately_from_simple_auto_ingest():
    # With link flagged as a subsystem, it must NOT be offered as a cheap auto-port.
    rep = triage(
        ["gain [Link]", "[App Fusion -4]"],
        subsystem_keywords={"link"},
    )
    assert "link" in rep.auto_ingest_subsystem
    assert "link" not in rep.auto_ingest
    assert "app fusion" in rep.auto_ingest  # non-subsystem stays simple
    # a subsystem keyword needing a port still blocks a naive full run
    assert rep.blocks_authoring


def test_flag_for_human_when_nobody_has_it():
    rep = triage(["This Digimon gains [Unchained]."])
    assert "unchained" in rep.flag_for_human
    assert rep.blocks_authoring


def test_numeric_param_normalized():
    rep = triage(["[App Fusion -4]", "[App Fusion -6]"])
    # both collapse to one base keyword with count 2
    assert rep.auto_ingest["app fusion"] == 2


def test_name_and_trait_lexicon_hits_not_flagged():
    rep = triage(["return [Greymon]", "1 of your [Machine] trait Digimon"])
    assert "greymon" in rep.name_hits
    assert "machine" in rep.trait_hits
    assert not rep.flag_for_human


def test_timing_and_grammar_ignored():
    rep = triage(["[On Play] [Once Per Turn] draw 1 card. [Main] do X."])
    for tok in ("on play", "once per turn", "main"):
        assert tok in rep.ignored
    assert not rep.flag_for_human and not rep.auto_ingest


def test_slash_list_trait_enumeration_all_marked_trait():
    # "[Social]/[Tool]/[Game] trait" — every token is a trait, not just Game.
    rep = triage(["1 of your [Social]/[Tool]/[Game] trait Digimon"])
    for t in ("social", "tool", "game"):
        assert t in rep.trait_hits
    assert not rep.flag_for_human


def test_whitespace_adjacent_brackets_are_separate_clauses():
    # "[Link] [Appmon] trait" — Link is the keyword (auto_ingest), Appmon a trait.
    # A bare space must NOT chain Link into the trait list (regression).
    rep = triage(["This Digimon has [Link] and is an [Appmon] trait Digimon"])
    assert "link" in rep.auto_ingest
    assert "appmon" in rep.trait_hits
    assert "link" not in rep.trait_hits


def test_fullwidth_token_with_nested_brackets_captured_whole():
    # ＜Decode ([Aegiomon] in name)＞ must capture the whole keyword token, not
    # truncate at the nested `]` (which mis-flagged 'decode ([aegiomon').
    rep = triage(
        ["＜Vortex ([Aegiomon] in its name)＞ does a thing"],
        rust_keywords={"vortex"},
    )
    assert "vortex" in rep.covered
    assert not rep.flag_for_human


def test_scan_detects_followed_by_trait():
    toks = scan_bracket_tokens("your [Aqua] trait and a [Blocker] keyword")
    d = dict(toks)
    assert d["Aqua"] is True
    assert d["Blocker"] is False


def test_integration_with_real_artifacts():
    # Uses the checked-in manifest + lexicons generated by tasks 2.1/2.2.
    texts = [
        "<Blocker> ...",                       # covered (Keyword enum)
        "gain [Link] ...",                     # covered (DSL-lowered: link_requirement)
        "delete a [Sea Animal] trait Digimon", # trait (positional)
        "return [Diaboromon] from trash",      # name_ref
        "This Digimon gains [Zephyrlock].",    # flag_for_human (novel, no collision)
    ]
    rep = triage_set_from_artifacts(texts, set_prefix="TEST")
    assert "blocker" in rep.covered
    # Link is a DCGO subsystem (ActivateClass), but the engine now lowers it
    # through the DSL (DigiLink substrate) -> covered, not a port to schedule.
    assert "link" in rep.covered
    assert "link" not in rep.auto_ingest_subsystem and "link" not in rep.auto_ingest
    assert "sea animal" in rep.trait_hits
    assert "diaboromon" in rep.name_hits
    assert "zephyrlock" in rep.flag_for_human
    assert rep.blocks_authoring


def test_name_trait_collision_is_a_known_limitation():
    # A would-be keyword that collides with a real card name/trait is classified
    # as that, NOT flagged. This is the documented collision limitation; the
    # manifest's proactive auto_ingest_candidates (task 2.1b) is the backstop.
    rep = triage(["This Digimon gains [Greymon]."])  # 'greymon' is in NAMES
    assert "greymon" in rep.name_hits
    assert "greymon" not in rep.flag_for_human


def test_printed_keyword_spellings_map_to_their_rust_home():
    # "Draw" / "Security A." are printed spellings of the DrawX /
    # SecurityAttack{Plus,Minus} variants; "Recovery" is a DSL step. None of
    # them is a new keyword (they flagged on BT26 and EX13 before this).
    rep = triage(
        ["＜Draw 2＞ ...", "gains ＜Security A. +1＞", "gets ＜Security A. -1＞",
         "＜Recovery +1 (Deck)＞"],
        rust_keywords=RUST | {"drawx", "securityattackplus", "securityattackminus"},
    )
    assert set(rep.covered) == {"draw", "security a.", "recovery"}
    assert not rep.flag_for_human


def test_positional_name_and_token_references_are_not_keywords():
    # EX13: "[X] in its name/text" and "[X] Token" refer to cards/tokens, and a
    # list run ending in such a suffix covers every item (NBSP as printed).
    rep = triage([
        "into a Digimon card with [Imperialdramon]\xa0in its name",
        "Add 1 Digimon card with [Huckmon] or [Sistermon]\xa0in its text",
        "You may play 1 [Hinukamuy] Token.",
        "play 1 [Atho, René & Por] Token",
    ])
    assert set(rep.name_hits) == {"imperialdramon", "huckmon", "sistermon",
                                  "hinukamuy", "atho, rené & por"}
    assert not rep.flag_for_human


def test_in_its_traits_list_with_other_than_is_a_trait_run():
    rep = triage([
        "1 Digimon card with [Beast], [Animal] or [Sovereign], other than "
        "[Sea Animal],\xa0in any of its traits among them"
    ])
    assert {"beast", "animal", "sovereign", "sea animal"} <= set(rep.trait_hits)
    assert not rep.flag_for_human


def test_keyword_before_a_bare_name_is_not_swallowed_by_the_name_rule():
    # "[Link] [Appmon] in its name": no list separator, so Link stays a keyword.
    rep = triage(["gain [Link] [Appmon] in its name"])
    assert "link" in rep.auto_ingest
    assert "appmon" in rep.name_hits


def test_token_named_elsewhere_in_the_set_is_a_name_everywhere():
    rep = triage([
        "Then, if you don't have [Atho, René & Por], you may play 1 "
        "[Atho, René & Por] Token.",
    ])
    assert rep.name_hits["atho, rené & por"] == 2
    assert not rep.flag_for_human


# ---- task 9.1: the false positives that made every real pool NO-GO -----------


def test_dsl_lowered_keywords_are_covered():
    # <Delay>, <Use Req.>, <Link +1> / [Link], <Detach>, <Succession>,
    # <Blast DNA Digivolve>, [Assembly] have no `Keyword` enum variant: the
    # engine runs them through DSL vocabulary (the manifest's
    # `dsl_lowered_keywords`). They flagged on every pool that used them.
    rep = triage(
        [
            "[Main] ＜Delay＞ (By trashing this card after the placing turn, ...)",
            "＜Use Req. ([CS] trait)＞ (Specified cards let you ignore color requirements.)",
            "＜Link +1＞ (Add 1 to this Digimon's maximum links.)",
            "Link Requirements [Link] Lv.3 or higher: Cost 2",
            "＜Detach ([Seven Code] trait)＞ (When this Digimon would leave ...)",
            "＜Succession ([Ceresmon])＞ (This Digimon gains all effects other than ＜Succession＞",
            "[Hand] [Counter] ＜Blast DNA Digivolve ([WarGreymon] + [MetalGarurumon])＞",
            "[Assembly] -6 [WarGreymon] x [MetalGarurumon]",
        ],
        card_names=NAMES | {"wargreymon", "metalgarurumon"},
        subsystem_keywords={"link", "blastdnadigivolve"},
        dsl_keywords={"delay", "usereq", "link", "detach", "succession",
                      "blastdnadigivolve", "assembly"},
    )
    assert set(rep.covered) == {"delay", "use req.", "link", "detach", "succession",
                                "blast dna digivolve", "assembly"}
    assert not rep.flag_for_human and not rep.auto_ingest_subsystem and not rep.auto_ingest
    assert not rep.blocks_authoring


def test_dsl_lowered_keyword_beats_the_dcgo_subsystem_class():
    # The DCGO complexity class only matters for a keyword the ENGINE lacks:
    # once the DSL lowers Link it is covered, not a port to schedule (ST22-09
    # blocked Rocks on this).
    rep = triage(["Link Requirements [Link] Lv.3 or higher: Cost 2"],
                 subsystem_keywords={"link"}, dsl_keywords={"link"})
    assert "link" in rep.covered
    assert not rep.auto_ingest_subsystem


def test_up_to_param_is_stripped_like_a_numeric_param():
    # BT7-040: "＜Digi-Burst up to 4＞" is <Digi-Burst N> with "up to".
    rep = triage(["[Main] [Once Per Turn] ＜Digi-Burst up to 4＞ (You may trash up to 4 ...)"],
                 rust_keywords=RUST | {"digiburst"})
    assert "digi-burst" in rep.covered
    assert not rep.flag_for_human


def test_names_and_traits_ending_in_a_number_or_parenthetical_resolve_unstripped():
    # Param stripping must not mangle a name/trait before the lexicon lookup:
    # [King Drasil_7D6], [Shoutmon EX6], [Belphemon (X Antibody)],
    # [Eater (Species Form)] are names; [Ver.3] is a trait.
    rep = triage(
        [
            "under a [King Drasil_7D6] in the breeding area",
            "By unsuspending 1 of your [Shoutmon EX6] and 1 of your [ShootingStarmon]",
            "When any of your Digimon digivolve into [Belphemon (X Antibody)], ...",
            "You may place 1 [Eater (Species Form)] from this Digimon's digivolution cards",
            "play 2 level 6 or lower [Composite], [Ver.3] or [Ver.5] Digimon cards",
        ],
        card_names=NAMES | {"king drasil_7d6", "shoutmon ex6", "shootingstarmon",
                            "belphemon (x antibody)", "eater (species form)"},
        traits=TRAITS | {"composite", "ver.3", "ver.5"},
    )
    assert {"king drasil_7d6", "shoutmon ex6", "belphemon (x antibody)",
            "eater (species form)"} <= set(rep.name_hits)
    assert {"ver.3", "ver.5"} <= set(rep.trait_hits)
    assert not rep.flag_for_human


def test_card_id_qualified_name_is_a_name():
    # EX2-039: "if it wasn't trashed by [EX2-039 Impmon]'s effect".
    rep = triage(["if it wasn't trashed by [EX2-039 Impmon]'s effect"],
                 card_names=NAMES | {"impmon"})
    assert "impmon" in rep.name_hits
    assert not rep.flag_for_human


def test_a_name_stem_resolves_a_card_family_reference():
    # BT7-083 names [Sistermon Noir]; the DB holds only "Sistermon Noir
    # (Awakened)". "Belphemon: Rage Mode" makes [Belphemon] a name too.
    rep = triage(
        ["You may place 1 [Sistermon Noir] from your hand or trash",
         "When you would play [Belphemon], ..."],
        card_names=NAMES | {"sistermon noir (awakened)", "belphemon: rage mode"},
    )
    assert {"sistermon noir", "belphemon"} <= set(rep.name_hits)
    assert not rep.flag_for_human


def test_a_name_stem_never_hides_a_known_keyword():
    # A card named "Rush (Something)" must not turn <Rush> into a name.
    rep = triage(["＜Rush＞ (This Digimon can attack the turn it comes into play.)"],
                 card_names=NAMES | {"rush (something)"})
    assert "rush" in rep.covered


def test_in_one_of_their_traits_is_a_trait_run():
    # BT10-056: "with [Vegetation], [Plant] or [Fairy] in one of their traits".
    rep = triage(["All of your other Digimon with [Vegetation], [Plant] or [Fairy] "
                  "in one of their traits gain ..."])
    assert {"vegetation", "plant", "fairy"} <= set(rep.trait_hits)
    assert not rep.flag_for_human


def test_bare_text_and_in_name_suffixes_are_name_references():
    # BT26-078 "[Chronomon] text or [Titan] trait Digimon";
    # BT26-060 "＜Succession (Lv.6 w/[Chronomon] in name)＞".
    rep = triage(["When any of your [Chronomon] text or [Titan] trait Digimon are played",
                  "Lv.6 w/[Chronomon] in name"])
    assert rep.name_hits["chronomon"] == 2
    assert "titan" in rep.trait_hits
    assert not rep.flag_for_human


def test_opponent_turn_timings_and_twice_per_turn_are_not_keywords():
    rep = triage([
        "[Start of Opponent's Turn] Declare 1 card category.",
        "[Start of Opponent’s Main Phase] By suspending 1 of your Digimon ...",
        "[End of Attack] [Twice Per Turn] You can unsuspend this Digimon",
    ])
    assert {"start of opponent's turn", "start of opponent's main phase",
            "twice per turn"} <= set(rep.ignored)
    assert not rep.flag_for_human


def test_a_made_up_keyword_still_flags_after_every_widening():
    # The gate must still bite: a keyword no engine, DCGO or lexicon knows is a
    # flag_for_human even in a text that exercises every new rule.
    rep = triage(
        ["＜Frobnicate 3＞ (A keyword nobody implements.) [Twice Per Turn] "
         "＜Delay＞ [Start of Opponent's Turn] [Sistermon Noir] [Ver.3] ＜Frobnicate up to 2＞"],
        card_names=NAMES | {"sistermon noir (awakened)"},
        traits=TRAITS | {"ver.3"},
        dsl_keywords={"delay"},
    )
    assert rep.flag_for_human == {"frobnicate": 2}
    assert rep.blocks_authoring


def test_real_artifacts_clear_the_reported_false_positives():
    # The task-9.1 cards, read from the committed cards.json + lexicons +
    # manifest: none of them may flag or need a port any more.
    import json

    from data_paths import CARDS_JSON

    rows = json.load(open(CARDS_JSON, encoding="utf-8"))
    cards = {r["card_id"]: r for r in rows} if isinstance(rows, list) else rows
    ids = ["P-238", "LM-047", "P-206", "P-236", "ST22-09", "BT25-075", "BT7-040",
           "BT7-083", "BT13-093", "BT19-090", "BT23-097", "BT22-080", "EX2-039",
           "BT10-056", "P-220", "BT26-078", "EX3-024", "EX5-065", "BT1-039", "AD1-025",
           "BT26-010", "BT26-032", "BT17-078"]
    fields = ("effect_description_eng", "inherited_effect_description_eng",
              "security_effect_description_eng")
    texts = [" ".join(str(cards[c].get(f) or "") for f in fields) for c in ids]
    rep = triage_set_from_artifacts(texts)
    assert not rep.flag_for_human, rep.summary()
    assert not rep.auto_ingest_subsystem and not rep.auto_ingest, rep.summary()
