"""Tests for the DCGO-oracle keyword gate (tasks 3.1 / 3.2 / 3.3 / 3.4)."""

from tools.author_set.keyword_gate import (
    scan_bracket_tokens,
    triage_set,
    triage_set_from_artifacts,
)

# Lexicons / registries kept tiny + explicit for the unit tests.
TRAITS = {"sea animal", "machine"}
NAMES = {"greymon", "diaboromon"}
RUST = {"blocker", "rush", "piercing", "vortex"}
DCGO = RUST | {"appfusion", "link", "petrification"}  # DCGO has 3 the enum lacks


def triage(texts, **over):
    kw = dict(traits=TRAITS, card_names=NAMES, rust_keywords=RUST, dcgo_available=DCGO)
    kw.update(over)
    return triage_set(texts, **kw)


def test_positional_trait_rule_beats_lexicon_and_param():
    # "[Aqua] trait" is a trait even though 'aqua' is absent from the lexicon.
    rep = triage(["delete 1 of your [Aqua] trait Digimon"])
    assert "aqua" in rep.trait_hits
    assert "aqua" in rep.lexicon_misses  # surfaced as a suggested lexicon addition
    assert not rep.flag_for_human


def test_covered_keyword():
    rep = triage(["<Blocker> This Digimon can block."])
    assert "blocker" in rep.covered
    assert not rep.auto_ingest and not rep.flag_for_human


def test_fullwidth_angle_bracket_keyword_detected():
    # Real Digimon keyword tokens use FULLWIDTH angle brackets (＜＞ U+FF1C/FF1E),
    # not ASCII <>. The scanner must match them or it misses every keyword like
    # ＜Blocker＞ / ＜Rush＞ / ＜Ascension＞ (BT25 regression).
    rep = triage(["＜Blocker＞ (This Digimon can block in the blocker timing.)"])
    assert "blocker" in rep.covered


def test_auto_ingest_when_dcgo_has_it():
    rep = triage(["[App Fusion -4] ...", "When this Digimon has [Link]..."])
    assert "app fusion" in rep.auto_ingest
    assert "link" in rep.auto_ingest


def test_subsystem_keyword_routed_separately_from_simple_auto_ingest():
    # With link flagged as a subsystem, it must NOT be offered as a cheap auto-port.
    rep = triage(
        ["gain [Link]", "[App Fusion -4]"],
        subsystem_keywords={"link"},
    )
    assert "link" in rep.auto_ingest_subsystem
    assert "link" not in rep.auto_ingest
    assert "app fusion" in rep.auto_ingest  # non-subsystem stays simple
    # a subsystem keyword needing a port still blocks a naive full run
    assert rep.blocks_authoring


def test_flag_for_human_when_nobody_has_it():
    rep = triage(["This Digimon gains [Unchained]."])
    assert "unchained" in rep.flag_for_human
    assert rep.blocks_authoring


def test_numeric_param_normalized():
    rep = triage(["[App Fusion -4]", "[App Fusion -6]"])
    # both collapse to one base keyword with count 2
    assert rep.auto_ingest["app fusion"] == 2


def test_name_and_trait_lexicon_hits_not_flagged():
    rep = triage(["return [Greymon]", "1 of your [Machine] trait Digimon"])
    assert "greymon" in rep.name_hits
    assert "machine" in rep.trait_hits
    assert not rep.flag_for_human


def test_timing_and_grammar_ignored():
    rep = triage(["[On Play] [Once Per Turn] draw 1 card. [Main] do X."])
    for tok in ("on play", "once per turn", "main"):
        assert tok in rep.ignored
    assert not rep.flag_for_human and not rep.auto_ingest


def test_slash_list_trait_enumeration_all_marked_trait():
    # "[Social]/[Tool]/[Game] trait" — every token is a trait, not just Game.
    rep = triage(["1 of your [Social]/[Tool]/[Game] trait Digimon"])
    for t in ("social", "tool", "game"):
        assert t in rep.trait_hits
    assert not rep.flag_for_human


def test_whitespace_adjacent_brackets_are_separate_clauses():
    # "[Link] [Appmon] trait" — Link is the keyword (auto_ingest), Appmon a trait.
    # A bare space must NOT chain Link into the trait list (regression).
    rep = triage(["This Digimon has [Link] and is an [Appmon] trait Digimon"])
    assert "link" in rep.auto_ingest
    assert "appmon" in rep.trait_hits
    assert "link" not in rep.trait_hits


def test_fullwidth_token_with_nested_brackets_captured_whole():
    # ＜Decode ([Aegiomon] in name)＞ must capture the whole keyword token, not
    # truncate at the nested `]` (which mis-flagged 'decode ([aegiomon').
    rep = triage(
        ["＜Vortex ([Aegiomon] in its name)＞ does a thing"],
        rust_keywords={"vortex"},
    )
    assert "vortex" in rep.covered
    assert not rep.flag_for_human


def test_scan_detects_followed_by_trait():
    toks = scan_bracket_tokens("your [Aqua] trait and a [Blocker] keyword")
    d = dict(toks)
    assert d["Aqua"] is True
    assert d["Blocker"] is False


def test_integration_with_real_artifacts():
    # Uses the checked-in manifest + lexicons generated by tasks 2.1/2.2.
    texts = [
        "<Blocker> ...",                       # covered
        "gain [Link] ...",                     # auto_ingest (DCGO has it, enum lacks)
        "delete a [Sea Animal] trait Digimon", # trait (positional)
        "return [Diaboromon] from trash",      # name_ref
        "This Digimon gains [Zephyrlock].",    # flag_for_human (novel, no collision)
    ]
    rep = triage_set_from_artifacts(texts, set_prefix="TEST")
    assert "blocker" in rep.covered
    # Link is a DCGO subsystem (ActivateClass) -> assess bucket, not cheap auto-port.
    assert "link" in rep.auto_ingest_subsystem
    assert "link" not in rep.auto_ingest
    assert "sea animal" in rep.trait_hits
    assert "diaboromon" in rep.name_hits
    assert "zephyrlock" in rep.flag_for_human
    assert rep.blocks_authoring


def test_name_trait_collision_is_a_known_limitation():
    # A would-be keyword that collides with a real card name/trait is classified
    # as that, NOT flagged. This is the documented collision limitation; the
    # manifest's proactive auto_ingest_candidates (task 2.1b) is the backstop.
    rep = triage(["This Digimon gains [Greymon]."])  # 'greymon' is in NAMES
    assert "greymon" in rep.name_hits
    assert "greymon" not in rep.flag_for_human
