"""Emit DCGO/Assets/Scripts/Script/Recording/ActionSpace.cs from the action-space JSON.

Pipeline:
  cargo run -p action-space-export | python emit_csharp.py --out <path>

This is the second half of the codegen bridge. The first half lives in the
sibling Rust binary and emits a JSON descriptor pulled live from
`digimon_engine::action::space`; this Python script consumes that JSON and
writes a C# static class with: matching constants, encoder helpers, and
range bounds. The DCGO `ActionEncoder` consumes only this generated file —
hand-edited C# constants are prohibited by the spec.

CI runs the full pipeline and diffs the result against the committed copy.
Drift → CI fails.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

# Header banner; emitted at the top of the generated file. The "DO NOT EDIT"
# message is for humans browsing DCGO source — it points them at the Rust
# crate where edits actually belong.
HEADER = """\
// <auto-generated>
//   This file is generated by `code/tools/action-space-export/emit_csharp.py`.
//
//   DO NOT EDIT BY HAND. Edits will be overwritten by the next codegen run.
//
//   Source of truth: code/digimon-engine/src/action/space.rs
//   Regenerate:
//     cargo run -p action-space-export | python code/tools/action-space-export/emit_csharp.py --out DCGO/Assets/Scripts/Script/Recording/ActionSpace.cs
//
//   CI verifies the committed copy matches the regenerated output. If you
//   see a CI failure pointing at this file, run the regenerate command and
//   commit the diff.
// </auto-generated>
"""

NAMESPACE_OPEN = """\
namespace Digimon.Recording
{
    /// <summary>
    /// Action-space layout mirrored from the Rust engine's
    /// <c>digimon_engine::action::space</c> module. Used by the DCGO
    /// <c>ActionEncoder</c> to translate in-client decisions into the
    /// 2192-ID action space the Rust engine and trained policies share.
    /// </summary>
    public static class ActionSpace
    {
"""

NAMESPACE_CLOSE = """\
    }
}
"""


def _comment(text: str, indent: str = "        ") -> str:
    """Render `text` as a /// XML doc comment block, indented under the class."""
    wrapped = textwrap.fill(text, width=92)
    return "\n".join(f"{indent}/// {line}" for line in wrapped.splitlines())


def emit(descriptor: dict[str, Any]) -> str:
    """Render the C# file as a single string from the JSON descriptor."""
    out: list[str] = [HEADER, NAMESPACE_OPEN]
    push = out.append

    schema_version = descriptor["schema_version"]
    action_space_size = descriptor["action_space_size"]

    push(_comment(
        "Schema version stamped into recordings produced by the DCGO mod. "
        "The Rust replay harness rejects recordings whose schema version "
        "exceeds the version it was built against."
    ))
    push(f"        public const uint SCHEMA_VERSION = {schema_version};")
    push("")

    push(_comment("Total action-space size. Used to size mask buffers."))
    push(f"        public const int ACTION_SPACE_SIZE = {action_space_size};")
    push("")

    # ── Single-ID constants ──────────────────────────────────────────────
    push("        // ── Single-ID constants ─────────────────────────────────────")
    push("")
    consts = descriptor["constants"]
    # Emit in stable alphabetical order so the file is diff-friendly.
    for name in sorted(consts.keys()):
        value = consts[name]
        push(f"        public const ushort {name} = {value};")
    push("")

    # ── Strides ──────────────────────────────────────────────────────────
    push("        // ── Stride / cardinality constants ─────────────────────────")
    push("")
    strides = descriptor["strides"]
    for name in sorted(strides.keys()):
        push(f"        public const ushort {name} = {strides[name]};")
    push("")

    # ── Ranges ───────────────────────────────────────────────────────────
    push("        // ── Range bounds (half-open [start, end)) ──────────────────")
    push("")
    ranges = descriptor["ranges"]
    for name in sorted(ranges.keys()):
        start, end = ranges[name]
        push(f"        public const ushort {name}_START = {start};")
        push(f"        public const ushort {name}_END   = {end};")
    push("")

    # ── Encoder helpers ──────────────────────────────────────────────────
    # Each formula: id = start + a * stride_a + b. Generated with bounds
    # checks so the encoder can fail loudly during recording rather than
    # silently emitting an out-of-range ID.
    push("        // ── Encoder helpers (mirror Rust encode_* functions) ──────")
    push("")

    formulas = descriptor["formulas"]
    formula_to_method = {
        "encode_attack":                 ("EncodeAttack",                "attacker", "target"),
        "encode_digivolve":              ("EncodeDigivolve",             "handIndex", "fieldIndex"),
        "encode_field_effect":           ("EncodeFieldEffect",           "permIndex", "effectIndex"),
        "encode_source_select":          ("EncodeSourceSelect",          "fieldIndex", "sourceIndex"),
        "encode_breeding_source_select": ("EncodeBreedingSourceSelect",  "carrierOwner", "sourceIndex"),
    }
    for rust_name, (method, a_name, b_name) in formula_to_method.items():
        f = formulas[rust_name]
        start = f["start"]
        stride_a = f["stride_a"]
        max_a = f["max_a"]
        max_b = f["max_b"]
        push(_comment(
            f"Mirrors Rust `{rust_name}`. Returns the encoded action ID. "
            f"Throws ArgumentOutOfRangeException if {a_name} >= {max_a} or "
            f"{b_name} >= {max_b}."
        ))
        push(f"        public static ushort {method}(int {a_name}, int {b_name})")
        push("        {")
        push(f"            if ((uint){a_name} >= {max_a}) throw new System.ArgumentOutOfRangeException(nameof({a_name}));")
        push(f"            if ((uint){b_name} >= {max_b}) throw new System.ArgumentOutOfRangeException(nameof({b_name}));")
        push(f"            return (ushort)({start} + {a_name} * {stride_a} + {b_name});")
        push("        }")
        push("")

    out.append(NAMESPACE_CLOSE)
    # Trailing newline so the file ends cleanly; helps editors.
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--in", dest="input",
        help="Read JSON descriptor from this file. Defaults to stdin.",
    )
    parser.add_argument(
        "--out", required=True,
        help="Write the generated ActionSpace.cs to this path.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Compare generated content to existing file at --out; exit non-zero if different. "
             "Does not write. Used by CI drift gate.",
    )
    args = parser.parse_args()

    if args.input:
        descriptor = json.loads(Path(args.input).read_text(encoding="utf-8"))
    else:
        descriptor = json.load(sys.stdin)

    generated = emit(descriptor)
    out_path = Path(args.out)

    if args.check:
        if not out_path.exists():
            print(f"DRIFT: {out_path} does not exist. Run without --check to generate.",
                  file=sys.stderr)
            return 2
        current = out_path.read_text(encoding="utf-8")
        if current != generated:
            print(f"DRIFT: {out_path} differs from regenerated output.",
                  file=sys.stderr)
            print("Run: cargo run -p action-space-export | python "
                  "code/tools/action-space-export/emit_csharp.py --out "
                  f"{out_path}", file=sys.stderr)
            return 1
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generated, encoding="utf-8")
    print(f"Wrote {out_path} ({len(generated)} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
