"""Playwright spec generation from a scenario fixture (test-emission).

Writes the fixture under `qa/scenarios/` (the source of truth) and scaffolds
a matching `<name>.scenario.spec.ts` under `code/frontend/e2e/` that stages
the fixture via `/debug` and asserts its engine assertions — reusing the
existing `./fixtures/debug-game` helpers. The generated spec is idempotent
and carries a banner directing edits to the fixture.

Runnable standalone for CI: `python -m digimon_scenario_mcp.spec_gen <name>`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

from . import fixtures as _fx

_SPEC_TEMPLATE = """\
// @generated by digimon-scenario-mcp — DO NOT EDIT.
// Edit the fixture (qa/scenarios/__NAME__.json) and regenerate instead.
import { test, expect } from '@playwright/test';
import { loadScenario, stageScenario, type ScenarioFixture } from './fixtures/debug-game';

// __TITLE__
test.describe('scenario: __NAME__', () => {
  test('engine assertions pass', async ({ page }) => {
    const fixture: ScenarioFixture = loadScenario('__NAME__');
    const game = await stageScenario(page, fixture);
    try {
      const result = await game.evaluate(fixture.assertions.engine ?? []);
      const detail = result.results
        .filter((r) => !r.passed)
        .map((r) => `${r.kind}: ${r.message}`)
        .join('\\n');

      if (fixture.readiness === 'blocked_on_card_impl') {
        test.info().annotations.push({ type: 'pending', description: 'blocked_on_card_impl' });
        return;
      }
      expect(result.all_passed, `engine assertions failed:\\n${detail}`).toBe(true);
    } finally {
      await game.delete();
    }
  });
});
"""


def render_spec_ts(name: str, fixture: dict[str, Any]) -> str:
    """Render the .spec.ts text for a fixture. Pure — no I/O."""
    title = str(fixture.get("title") or name).replace("\n", " ")
    return _SPEC_TEMPLATE.replace("__NAME__", name).replace("__TITLE__", title)


def resolve_e2e_dir(explicit: Optional[Path] = None) -> Optional[Path]:
    if explicit is not None:
        return explicit if explicit.is_dir() else None
    here = Path.cwd().resolve()
    for d in (here, *here.parents):
        cand = d / "code" / "frontend" / "e2e"
        if cand.is_dir():
            return cand
    return None


def generate_spec(
    fixture: dict[str, Any],
    name: str,
    scenarios_dir: Optional[Path],
    e2e_dir: Optional[Path],
) -> dict[str, Any]:
    """Persist the fixture + scaffold its Playwright spec. Returns paths."""
    saved = _fx.save_fixture(scenarios_dir, name, fixture)
    if not saved.get("ok"):
        return saved
    if e2e_dir is None or not e2e_dir.is_dir():
        return {"ok": False, "error": "e2e_dir not resolved (pass --e2e-dir)"}
    spec_path = e2e_dir / f"{name}.scenario.spec.ts"
    try:
        spec_path.write_text(render_spec_ts(name, fixture), encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"could not write spec: {exc}"}
    return {
        "ok": True,
        "name": name,
        "fixture_path": saved["path"],
        "spec_path": str(spec_path),
    }


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="digimon-scenario-spec-gen",
        description="Generate a Playwright .spec.ts from a saved scenario fixture.",
    )
    parser.add_argument("name", help="Fixture name (without .json) under qa/scenarios/.")
    parser.add_argument("--scenarios-dir", type=Path, default=None)
    parser.add_argument("--e2e-dir", type=Path, default=None)
    args = parser.parse_args(argv)

    scenarios_dir = _fx.resolve_scenarios_dir(args.scenarios_dir)
    loaded = _fx.load_fixture(scenarios_dir, args.name)
    if not loaded.get("ok"):
        print(json.dumps(loaded), file=sys.stderr)
        return 1
    result = generate_spec(
        loaded["fixture"], args.name, scenarios_dir, resolve_e2e_dir(args.e2e_dir)
    )
    print(json.dumps(result, indent=2))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
