"""Admin release management router for Tauri auto-updater.

Writes: /admin/releases/*  (all require ROLE_ADMIN)
The public read surface is the static manifest at
  <SPACES_CDN_URL or endpoint>/updates/<channel>/latest.json
which is regenerated by this module on publish/unpublish.
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timezone

from botocore.exceptions import ClientError
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from server.db.auth import ROLE_ADMIN, require_roles
from server.db.database import get_db
from server.db.models import AppRelease, AppReleaseArtifact, User
from server.db.schemas import (
    AppReleaseArtifactUploadSlot,
    AppReleaseConfirmRequest,
    AppReleaseConfirmResponse,
    AppReleaseCreateRequest,
    AppReleaseCreateResponse,
    AppReleaseResponse,
    AppReleaseUpdateRequest,
    ListAppReleasesResponse,
    RegenerateManifestResponse,
    ReleaseManifest,
    UnpublishResponse,
)
from server.storage import spaces

admin_router = APIRouter(prefix="/admin/releases", tags=["admin-releases"])

UPLOAD_URL_TTL = 900  # seconds

_PRODUCT_SLUG = "digimon-tcg"
_TARGET_EXTENSION = {
    "windows-x86_64": "x86_64-setup.exe",
    "linux-x86_64": "x86_64.AppImage",
}


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _artifact_filename(version: str, target: str) -> str:
    ext = _TARGET_EXTENSION[target]
    return f"{_PRODUCT_SLUG}-{version}-{ext}"


def _artifact_spaces_key(release_id: str, filename: str) -> str:
    return f"releases/{release_id}/{filename}"


@admin_router.post(
    "",
    response_model=AppReleaseCreateResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_release(
    request: AppReleaseCreateRequest,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseCreateResponse:
    """Create an AppRelease row and return a presigned PUT URL per target."""
    existing = await db.scalar(
        select(AppRelease).where(
            AppRelease.channel == request.channel,
            AppRelease.version == request.version,
        )
    )
    if existing is not None:
        raise HTTPException(
            status_code=409,
            detail=(
                f"release already exists for channel={request.channel} "
                f"version={request.version}"
            ),
        )

    release = AppRelease(
        version=request.version,
        channel=request.channel,
        engine_commit=request.engine_commit,
        min_version=request.min_version,
        release_notes=request.release_notes,
        state="pending",
        published=False,
    )
    db.add(release)
    await db.flush()  # populate release.id via _new_uuid default

    slots: list[AppReleaseArtifactUploadSlot] = []
    for target in request.targets:
        filename = _artifact_filename(request.version, target)
        key = _artifact_spaces_key(release.id, filename)
        artifact = AppReleaseArtifact(
            release_id=release.id,
            target=target,
            spaces_key=key,
            filename=filename,
        )
        db.add(artifact)
        upload_url = await asyncio.to_thread(
            spaces.generate_presigned_put,
            key,
            UPLOAD_URL_TTL,
            "application/octet-stream",
        )
        slots.append(
            AppReleaseArtifactUploadSlot(
                target=target,
                upload_url=upload_url,
                spaces_key=key,
                filename=filename,
                expires_in=UPLOAD_URL_TTL,
            )
        )

    await db.commit()

    return AppReleaseCreateResponse(
        release_id=release.id,
        version=release.version,
        channel=release.channel,
        artifacts=slots,
    )


@admin_router.post(
    "/{release_id}/artifacts/{target}/confirm",
    response_model=AppReleaseConfirmResponse,
)
async def confirm_artifact(
    release_id: str,
    target: str,
    request: AppReleaseConfirmRequest,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseConfirmResponse:
    """Confirm CI upload: HEAD the object, stream SHA-256, store signature."""
    artifact = await db.scalar(
        select(AppReleaseArtifact).where(
            AppReleaseArtifact.release_id == release_id,
            AppReleaseArtifact.target == target,
        )
    )
    if artifact is None:
        raise HTTPException(status_code=404, detail="artifact not found")

    # HEAD first so we 422 cleanly on missing upload rather than crashing
    # inside the streaming hash.
    try:
        await asyncio.to_thread(spaces.head_object, artifact.spaces_key)
    except ClientError as e:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Spaces object {artifact.spaces_key} not present "
                f"(CI upload failed?): {e}"
            ),
        )

    try:
        sha256_hex, total_bytes = await asyncio.to_thread(
            spaces.stream_sha256, artifact.spaces_key
        )
    except ClientError as e:
        raise HTTPException(status_code=422, detail=f"stream_sha256 failed: {e}")

    artifact.file_sha256 = sha256_hex
    artifact.file_size_bytes = total_bytes
    artifact.signature_b64 = request.signature_b64
    await db.commit()

    return AppReleaseConfirmResponse(
        release_id=release_id,
        target=target,
        file_sha256=sha256_hex,
        file_size_bytes=total_bytes,
    )


async def _build_manifest(release: AppRelease) -> dict:
    """Serialize a release + its artifacts into the Tauri-compatible
    manifest JSON shape."""
    platforms: dict[str, dict] = {}
    for art in release.artifacts:
        if art.file_sha256 is None or art.signature_b64 is None:
            raise HTTPException(
                status_code=409,
                detail=(
                    f"artifact {art.target} is unconfirmed; "
                    "confirm it before publish"
                ),
            )
        platforms[art.target] = {
            "signature": art.signature_b64,
            "url": spaces.public_url(art.spaces_key),
        }
    pub_iso = (release.published_at or _utcnow()).isoformat().replace("+00:00", "Z")
    return {
        "version": release.version,
        "pub_date": pub_iso,
        "notes": release.release_notes,
        "platforms": platforms,
        "min_version": release.min_version,
        "engine_commit": release.engine_commit,
        "channel": release.channel,
        "release_id": release.id,
    }


def _manifest_key(channel: str) -> str:
    return f"updates/{channel}/latest.json"


async def _rewrite_channel_manifest(
    db: AsyncSession, channel: str
) -> dict | None:
    """Regenerate updates/<channel>/latest.json from the newest published
    release on that channel. Returns the manifest dict, or None (and
    deletes the Spaces object) if no published release exists.
    """
    release = await db.scalar(
        select(AppRelease)
        .where(
            AppRelease.channel == channel,
            AppRelease.published == True,  # noqa: E712
        )
        .order_by(AppRelease.published_at.desc())
        .limit(1)
    )
    key = _manifest_key(channel)
    if release is None:
        try:
            await asyncio.to_thread(spaces.delete_object, key)
        except ClientError:
            pass  # 404 is fine
        return None
    manifest = await _build_manifest(release)
    await asyncio.to_thread(spaces.put_json, key, manifest, 60)
    return manifest


@admin_router.post(
    "/{release_id}/publish",
    response_model=AppReleaseResponse,
)
async def publish_release(
    release_id: str,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseResponse:
    """Mark a release published, unpublish others on same channel, rewrite
    the channel manifest in Spaces."""
    release = await db.get(AppRelease, release_id)
    if release is None:
        raise HTTPException(status_code=404, detail="release not found")

    for art in release.artifacts:
        if art.file_sha256 is None or art.signature_b64 is None:
            raise HTTPException(
                status_code=409,
                detail=f"artifact {art.target} is unconfirmed",
            )

    # Unpublish any other row on this channel
    others = await db.scalars(
        select(AppRelease).where(
            AppRelease.channel == release.channel,
            AppRelease.published == True,  # noqa: E712
            AppRelease.id != release.id,
        )
    )
    for row in others.all():
        row.published = False

    release.state = "uploaded"
    release.published = True
    release.published_at = _utcnow()
    await db.flush()

    await _rewrite_channel_manifest(db, release.channel)
    await db.commit()
    await db.refresh(release)
    return AppReleaseResponse.model_validate(release)


@admin_router.get(
    "",
    response_model=ListAppReleasesResponse,
)
async def list_releases(
    channel: str | None = Query(default=None),
    published: bool | None = Query(default=None),
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> ListAppReleasesResponse:
    """List releases, optionally filtered by channel and/or published."""
    stmt = select(AppRelease).order_by(AppRelease.created_at.desc())
    if channel is not None:
        stmt = stmt.where(AppRelease.channel == channel)
    if published is not None:
        stmt = stmt.where(AppRelease.published == published)
    rows = (await db.scalars(stmt)).all()
    return ListAppReleasesResponse(
        releases=[AppReleaseResponse.model_validate(r) for r in rows]
    )


# NOTE: regenerate-manifest is declared BEFORE any `/{release_id}` routes so
# FastAPI's path matcher can never resolve its static segment to a release_id.
@admin_router.post(
    "/regenerate-manifest",
    response_model=RegenerateManifestResponse,
)
async def regenerate_manifest(
    channel: str = Query(...),
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> RegenerateManifestResponse:
    """Recovery path: rewrite updates/<channel>/latest.json from current DB."""
    manifest = await _rewrite_channel_manifest(db, channel)
    await db.commit()
    return RegenerateManifestResponse(
        channel=channel,
        current_version=manifest["version"] if manifest else None,
        manifest=ReleaseManifest.model_validate(manifest) if manifest else None,
    )


@admin_router.post(
    "/{release_id}/unpublish",
    response_model=UnpublishResponse,
)
async def unpublish_release(
    release_id: str,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> UnpublishResponse:
    """Mark a release unpublished; rewrite manifest from next-newest previously-
    published row (rollback), or delete the Spaces manifest if none remain.

    Rollback semantic: the predecessor was silently unpublished at publish-time
    by `publish_release`, so re-promote the next-most-recent release on the
    same channel (by `published_at DESC`) that has been confirmed + published
    before. If none exists, delete the manifest.
    """
    release = await db.get(AppRelease, release_id)
    if release is None:
        raise HTTPException(status_code=404, detail="release not found")
    release.published = False
    await db.flush()

    # Find the next candidate to re-promote: any release on this channel
    # that was previously published (has published_at) and is not the row
    # we just unpublished.
    candidate = await db.scalar(
        select(AppRelease)
        .where(
            AppRelease.channel == release.channel,
            AppRelease.id != release.id,
            AppRelease.published_at.is_not(None),
        )
        .order_by(AppRelease.published_at.desc())
        .limit(1)
    )
    if candidate is not None:
        # Re-promote: confirm all artifacts are still present before flipping
        for art in candidate.artifacts:
            if art.file_sha256 is None or art.signature_b64 is None:
                # Can't safely rollback to this one; fall through and delete
                candidate = None
                break
    if candidate is not None:
        candidate.published = True
        await db.flush()

    manifest = await _rewrite_channel_manifest(db, release.channel)
    await db.commit()
    return UnpublishResponse(
        channel=release.channel,
        current_version=manifest["version"] if manifest else None,
    )


@admin_router.patch(
    "/{release_id}",
    response_model=AppReleaseResponse,
)
async def update_release(
    release_id: str,
    request: AppReleaseUpdateRequest,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseResponse:
    """Mutate release_notes and/or min_version; rewrite manifest if published."""
    release = await db.get(AppRelease, release_id)
    if release is None:
        raise HTTPException(status_code=404, detail="release not found")
    if request.release_notes is not None:
        release.release_notes = request.release_notes
    if request.min_version is not None:
        release.min_version = request.min_version
    await db.flush()
    if release.published:
        await _rewrite_channel_manifest(db, release.channel)
    await db.commit()
    await db.refresh(release)
    return AppReleaseResponse.model_validate(release)


@admin_router.delete(
    "/{release_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
async def delete_release(
    release_id: str,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
):
    """Delete a release; refuse if published. Best-effort Spaces cleanup."""
    release = await db.get(AppRelease, release_id)
    if release is None:
        raise HTTPException(status_code=404, detail="release not found")
    if release.published:
        raise HTTPException(
            status_code=409,
            detail="release is published; unpublish before delete",
        )
    for art in release.artifacts:
        try:
            await asyncio.to_thread(spaces.delete_object, art.spaces_key)
        except ClientError:
            pass
    await db.delete(release)
    await db.commit()
