"""Game session endpoints — Rust engine backed.

Engine-only router (no DB, no auth). The desktop client dispatches the
same operations through Tauri `invoke()` into the Rust engine; this
router exposes the same Rust engine over HTTP for the browser-dev path.

Previously this router used `engine_py_legacy.engine.runners`. That
path was hollowed during the Rust migration (CLAUDE.md rule #22:
production code MUST NOT import from `engine_py_legacy.*`). The
legacy runners also depend on Python card scripts that bit-rotted
when the EffectTiming enum was refactored — `ST14-12` still
references the removed `DelaySkill` value, blocking game creation.

Replacing the legacy backend with `RustHeadlessGame` (via PyO3
bindings) fixes both: no more legacy import, no more script bit-rot.
The HTTP response shape is kept identical so the frontend's
`gameApi.ts` HTTP fallback drops in without DTO translation —
`RustHeadlessGame.to_ui_json()` already returns the camelCase shape
the React `GameState` type speaks.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass, field
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, HTTPException
from digimon_engine import RustDebugGame, RustHeadlessGame, parse_deck

from server.routers.schemas import (
    CreateGameRequest,
    GameActionRequest,
    SurrenderRequest,
)
from server.routers.seed_utils import seed_to_wire
from server.routers.state import active_games

router = APIRouter(tags=["games"])


@dataclass
class GameMeta:
    """Per-session non-engine state — drives the agent-vs-human autoplay
    loop and stores logs/events the engine emits during a step so the
    HTTP response can carry them back. Mirrors the role `InteractiveGame`
    used to play in the legacy stack.

    Also retains the inputs needed to rebuild the engine from scratch so
    `/games/<id>/undo` can pop the last human action and replay the rest
    deterministically (`deck1` / `deck2` / `seed` / `human_action_history`).
    Agent actions are *not* stored — they're regenerated by the greedy
    policy on replay, which is deterministic given the same seed and
    pre-history."""

    p1_human: bool
    p2_human: bool
    last_log: list[str]
    last_events: list[dict[str, Any]]
    player_labels: dict[int, str]
    deck1: list[str]
    deck2: list[str]
    seed: int
    human_action_history: list[int] = field(default_factory=list)


game_meta: dict[str, GameMeta] = {}


def _require_game(game_id: str):
    """Return the active runner. Accepts both `RustHeadlessGame` (live play)
    and `RustDebugGame` (scenario-staged) — they share the same play surface
    (`step` / `get_action_mask` / `to_ui_json` / events), so a game staged
    via `/debug` can be driven through these live `/games` routes."""
    runner = active_games.get(game_id)
    if not runner:
        raise HTTPException(status_code=404, detail="Game not found")
    if not isinstance(runner, (RustHeadlessGame, RustDebugGame)):
        raise HTTPException(
            status_code=500,
            detail="Game session is not a Rust runner — incompatible runner registered",
        )
    return runner


def _require_meta(game_id: str) -> GameMeta:
    meta = game_meta.get(game_id)
    if not meta:
        raise HTTPException(status_code=404, detail="Game metadata missing")
    return meta


def _is_human_turn(game: RustHeadlessGame, meta: GameMeta) -> bool:
    """Python player-id convention: 1 → meta.p1_human, 2 → meta.p2_human."""
    cur = game.current_player_id
    if cur == 1:
        return meta.p1_human
    if cur == 2:
        return meta.p2_human
    return False


def _autoplay_agent_turns(
    game: RustHeadlessGame,
    meta: GameMeta,
    *,
    log_buffer: list[str],
    event_buffer: list[dict[str, Any]],
    max_steps: int = 4096,
) -> None:
    """Step through agent decisions until the engine wants a human or the
    game ends. Mirrors the legacy `InteractiveGame.run_step` agent loop.

    Per-step logs/events drain into the caller-supplied buffers so the
    HTTP response carries the cumulative trace from this call (matching
    how `gameApi.ts` consumes `logs` and `events`)."""
    steps = 0
    while not game.is_game_over and steps < max_steps:
        if _is_human_turn(game, meta):
            return
        action = game.greedy_action()
        game.step(action)
        for log_line in game.get_last_log():
            log_buffer.append(log_line)
        for ev in game.get_events_since_last_step():
            event_buffer.append(ev)
        steps += 1


def _build_state_payload(
    game: RustHeadlessGame,
    meta: GameMeta,
    *,
    logs: list[str] | None = None,
    events: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Common response builder used by /actions, /steps, /state, etc.
    Keys mirror the legacy router's contract so the frontend's
    `gameApi.ts` HTTP fallback can consume the same shape it consumes
    from Tauri responses."""
    return {
        "state": game.to_ui_json(),
        "action_mask": game.get_action_mask().tolist(),
        "is_game_over": game.is_game_over,
        "logs": logs or [],
        "events": events or [],
        "is_human_turn": _is_human_turn(game, meta),
        # True while a non-human agent still has actions to take — a paced
        # client should POST /games/{id}/agent-step for the next beat.
        # Unpaced responses always report False (autoplay drained to a human
        # decision point or game end). Key name mirrors the desktop wire's
        # `agent_pending` (cross-wire parity, add-bot-action-pacing).
        "agent_pending": not game.is_game_over and not _is_human_turn(game, meta),
        "player_labels": meta.player_labels,
        "seed": seed_to_wire(meta.seed),
    }


@router.post("/games")
@router.post("/game/create", include_in_schema=False)
def create_game(request: CreateGameRequest):
    """Create a new Rust-engine-backed session.

    Accepts the same `CreateGameRequest` schema the legacy router took.
    Trained-policy support is currently dropped — only `greedy` is
    available for agent players in the HTTP path; the desktop Tauri
    path still has trained-policy support via the ONNX inference
    state. Browser-dev is for testing, not for matchmaking against
    trained policies, so this trade-off is acceptable for now."""
    try:
        deck1 = parse_deck(request.deck1_raw) if request.deck1_raw else request.deck1
        deck2 = parse_deck(request.deck2_raw) if request.deck2_raw else request.deck2
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=f"Deck parsing error: {exc}")

    if not deck1 or not deck2:
        raise HTTPException(status_code=400, detail="Both decks must be provided")

    game_id = str(uuid4())
    # Scenario staging: honor an explicit `seed` if provided, otherwise
    # generate a cryptographic one. Either way the seed lands in meta so
    # /debug can export it and a later create can replay it. The engine
    # accepts u64; `secrets.randbits(64)` stays inside that range.
    seed = request.seed if request.seed is not None else secrets.randbits(64)
    try:
        game = RustHeadlessGame(deck1, deck2, False, False, False, seed)
    except Exception as exc:  # PyValueError from the Rust binding
        raise HTTPException(status_code=400, detail=f"Engine construction failed: {exc}")

    p1_human = request.player1_type.lower() == "human"
    p2_human = request.player2_type.lower() == "human"
    meta = GameMeta(
        p1_human=p1_human,
        p2_human=p2_human,
        last_log=[],
        last_events=[],
        player_labels={
            1: "You" if p1_human else "Agent",
            2: "You" if p2_human else "Agent",
        },
        deck1=list(deck1),
        deck2=list(deck2),
        seed=seed,
    )

    active_games[game_id] = game
    game_meta[game_id] = meta

    # If the opening turn belongs to an agent, advance until a human
    # decision (or game end). All emitted logs/events flow into the
    # initial response so the client never misses the agent's prelude.
    # Paced mode caps the prelude at ONE agent action so the client can
    # render each beat (it drives the rest via /agent-step) — but never
    # while an action_script is replaying, since the script's human actions
    # require agents to fully resolve between them (staging, not
    # presentation).
    paced_create = request.paced and not request.action_script
    log_buffer: list[str] = []
    event_buffer: list[dict[str, Any]] = []
    _autoplay_agent_turns(
        game,
        meta,
        log_buffer=log_buffer,
        event_buffer=event_buffer,
        max_steps=1 if paced_create else 4096,
    )

    # Scenario fast-forward: replay each scripted HUMAN action in order,
    # auto-playing agent turns between them, to land in a mid-game state
    # without playing through manually. Recording each into
    # `human_action_history` keeps the script undo-able and replayable
    # exactly like live actions. This is the lightweight precursor to the
    # full `/debug` direct-staging surface (see the
    # add-ui-scenario-test-substrate change): action_script reaches a
    # state by *replaying decisions*, whereas /debug injects board state
    # directly. Both share the seed + history replay machinery `/undo`
    # uses.
    if request.action_script:
        for action_id in request.action_script:
            if game.is_game_over:
                raise HTTPException(
                    status_code=400,
                    detail=(
                        f"action_script reached a finished game before applying "
                        f"action {action_id}"
                    ),
                )
            # Validate against the live mask BEFORE stepping. The engine
            # treats an illegal/out-of-range action as a silent no-op, so
            # without this guard a wrong scripted action would quietly
            # diverge the scenario instead of failing. Scenario staging
            # must fail loud (design: validate-on-stage).
            mask = game.get_action_mask().tolist()
            aid = int(action_id)
            if aid < 0 or aid >= len(mask) or mask[aid] != 1:
                raise HTTPException(
                    status_code=400,
                    detail=(
                        f"action_script action {aid} is not legal at this "
                        f"point (current player {game.current_player_id}, "
                        f"phase {game.to_ui_json().get('currentPhase')})"
                    ),
                )
            meta.human_action_history.append(aid)
            try:
                game.step(aid)
            except Exception as exc:
                meta.human_action_history.pop()
                raise HTTPException(
                    status_code=400,
                    detail=f"action_script step {action_id} failed: {exc}",
                )
            for log_line in game.get_last_log():
                log_buffer.append(log_line)
            for ev in game.get_events_since_last_step():
                event_buffer.append(ev)
            _autoplay_agent_turns(
                game, meta, log_buffer=log_buffer, event_buffer=event_buffer
            )

    return {
        "game_id": game_id,
        **_build_state_payload(game, meta, logs=log_buffer, events=event_buffer),
    }


@router.post("/games/{game_id}/actions")
@router.post("/game/{game_id}/action", include_in_schema=False)
def game_action(game_id: str, request: GameActionRequest):
    """Execute a single human action in an active session."""
    game = _require_game(game_id)
    meta = _require_meta(game_id)

    if game.is_game_over:
        raise HTTPException(status_code=400, detail="Game already over")

    current_player_id = game.current_player_id
    # `RustHeadlessGame` doesn't expose `memory` as a top-level field
    # before/after a step (only via `to_ui_json`). We capture the
    # before-state from the UI JSON for action_context parity with the
    # legacy router. This is cheap (engine has the field in hand).
    pre = game.to_ui_json()
    memory_before = pre.get("memoryGauge", 0)
    phase_before = pre.get("currentPhase", "")
    turn_before = pre.get("turnCount", 0)

    # Record the human action BEFORE stepping so undo can replay this
    # decision-stream-minus-last. Agent steps that follow inside
    # `_autoplay_agent_turns` are *not* recorded — the greedy policy is
    # deterministic against (seed + human_action_history), so replay
    # regenerates them.
    meta.human_action_history.append(int(request.action))
    try:
        game.step(int(request.action))
    except Exception as exc:
        # Roll the history back so a failed action doesn't leave a phantom
        # entry that would diverge a later undo replay.
        meta.human_action_history.pop()
        raise HTTPException(status_code=400, detail=f"Step failed: {exc}")

    log_buffer = list(game.get_last_log())
    event_buffer = list(game.get_events_since_last_step())

    # If after the human step the next decision is an agent's, advance
    # through agent turns automatically. Paced requests cap this at ONE
    # agent action so the client can render each beat and pull the rest
    # via /agent-step.
    _autoplay_agent_turns(
        game,
        meta,
        log_buffer=log_buffer,
        event_buffer=event_buffer,
        max_steps=1 if request.paced else 4096,
    )

    payload = _build_state_payload(game, meta, logs=log_buffer, events=event_buffer)
    payload["action_context"] = {
        "player_id": current_player_id,
        "action_id": request.action,
        "phase": phase_before,
        "memory_before": memory_before,
        "memory_after": game.to_ui_json().get("memoryGauge", 0),
        "turn": turn_before,
    }
    return payload


@router.post("/games/{game_id}/steps")
@router.post("/game/{game_id}/step", include_in_schema=False)
def game_step(game_id: str):
    """Advance the session until the next human decision or game end.
    No-op if the current decision is already a human's."""
    game = _require_game(game_id)
    meta = _require_meta(game_id)

    log_buffer: list[str] = []
    event_buffer: list[dict[str, Any]] = []
    _autoplay_agent_turns(game, meta, log_buffer=log_buffer, event_buffer=event_buffer)
    return _build_state_payload(game, meta, logs=log_buffer, events=event_buffer)


@router.post("/games/{game_id}/agent-step")
def game_agent_step(game_id: str):
    """Advance exactly ONE agent action (paced mode, add-bot-action-pacing).

    The paced client loop: render the previous response's beat, wait the
    user-configured delay, then POST here while `agent_pending` is true.
    No-op (returns current state) if the decision is already a human's or
    the game is over — safe against double-fires from a re-rendering
    client."""
    game = _require_game(game_id)
    meta = _require_meta(game_id)

    log_buffer: list[str] = []
    event_buffer: list[dict[str, Any]] = []
    _autoplay_agent_turns(
        game, meta, log_buffer=log_buffer, event_buffer=event_buffer, max_steps=1
    )
    return _build_state_payload(game, meta, logs=log_buffer, events=event_buffer)


@router.get("/games/{game_id}/state")
@router.get("/game/{game_id}/state", include_in_schema=False)
def game_state(game_id: str):
    """Return the current `to_ui_json` snapshot."""
    game = _require_game(game_id)
    meta = _require_meta(game_id)
    state = dict(game.to_ui_json())
    state["seed"] = seed_to_wire(meta.seed)
    return state


@router.post("/games/{game_id}/export-scenario")
def export_scenario(game_id: str):
    """Capture the current full-information board as a scenario fixture
    (`qa/scenarios/` schema, empty assertions). Works for any active game —
    a normal `RustHeadlessGame` or a debug-staged `RustDebugGame` — because
    both expose the one engine `to_scenario()` primitive. The returned
    fixture re-stages (via `/debug`) to the identical board.

    Engine-only route: no DB/auth dependency."""
    game = _require_game(game_id)
    try:
        return game.to_scenario()
    except Exception as exc:  # pragma: no cover - defensive
        raise HTTPException(status_code=400, detail=f"Capture failed: {exc}")


@router.get("/games/{game_id}/action-mask")
@router.get("/game/{game_id}/mask", include_in_schema=False)
def game_mask(game_id: str):
    """Return the current action mask."""
    game = _require_game(game_id)
    return {"action_mask": game.get_action_mask().tolist()}


@router.get("/games/{game_id}/decoded-actions")
@router.get("/game/{game_id}/decoded-actions", include_in_schema=False)
def game_decoded_actions(game_id: str):
    """Decoded list of every currently-legal action for the current decision
    player, each carrying source-card and effect identity (`card_name`,
    `effect_name`, `source_zone`, `source_index`, `label`). The React action
    bar renders activatable effects from this list instead of re-deriving
    action semantics from raw mask bit-ranges. Mirrors the desktop
    `rust_get_decoded_actions` Tauri command (same `ActionExplanation` shape).

    Engine-only route: no DB/auth dependency."""
    game = _require_game(game_id)
    return {"decoded_actions": game.legal_decoded_actions()}


@router.post("/games/{game_id}/surrender")
def surrender_game(game_id: str, request: SurrenderRequest):
    """Concede on behalf of `player_id`. Player IDs are 1 or 2 (Python
    convention); the Rust binding translates to its 0/1 internal IDs."""
    game = _require_game(game_id)
    meta = _require_meta(game_id)
    if game.is_game_over:
        raise HTTPException(status_code=400, detail="Game is already over.")
    try:
        game.concede(int(request.player_id))
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Concede failed: {exc}")
    logs = list(game.get_last_log())
    events = list(game.get_events_since_last_step())
    payload = _build_state_payload(game, meta, logs=logs, events=events)
    payload["surrendered_by"] = request.player_id
    return payload


@router.post("/games/{game_id}/undo")
def undo_game(game_id: str):
    """Step the session backward by one human action — pops the last
    entry from `meta.human_action_history`, rebuilds the engine from the
    original decks + seed, and replays the remaining history (autoplaying
    agent turns between each replayed human action). Returns the same
    state payload shape as `/steps` so the frontend can refresh in place.

    Idempotent at history-empty: replaying zero actions just returns the
    fresh opening state. No-op if no human action was ever recorded.

    This is a debugging affordance for the browser-dev workflow — the
    desktop Tauri path doesn't expose it and shouldn't be relied on for
    real gameplay (an actual undo would change the meaning of any RL
    training trace)."""
    runner = active_games.get(game_id)
    if not runner or not isinstance(runner, RustHeadlessGame):
        raise HTTPException(status_code=404, detail="Game not found")
    meta = _require_meta(game_id)

    if not meta.human_action_history:
        # Nothing to undo — return the current state so the client can
        # still refresh its view.
        return _build_state_payload(runner, meta, logs=[], events=[])

    # Drop the most recent human action.
    meta.human_action_history.pop()

    # Rebuild the engine from the same decks + seed. The opening agent
    # turns (if any) are auto-played to mirror what the original /games
    # POST response would have produced.
    try:
        new_game = RustHeadlessGame(meta.deck1, meta.deck2, False, False, False, meta.seed)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Engine rebuild failed: {exc}")

    log_buffer: list[str] = []
    event_buffer: list[dict[str, Any]] = []
    # Opening agent-vs-agent stretch (e.g. if player 1 is an agent).
    _autoplay_agent_turns(new_game, meta, log_buffer=log_buffer, event_buffer=event_buffer)

    # Replay each remaining human action; between each, the engine may
    # surrender control back to an agent until the next human decision.
    for action_id in meta.human_action_history:
        if new_game.is_game_over:
            break
        try:
            new_game.step(int(action_id))
        except Exception as exc:
            # An action that no longer validates against the rebuilt state
            # means our replay assumption broke. Surface the divergence so
            # the user knows undo can't continue rather than silently
            # entering an undefined state.
            raise HTTPException(
                status_code=500,
                detail=f"Undo replay diverged at action {action_id}: {exc}",
            )
        for log_line in new_game.get_last_log():
            log_buffer.append(log_line)
        for ev in new_game.get_events_since_last_step():
            event_buffer.append(ev)
        _autoplay_agent_turns(
            new_game, meta, log_buffer=log_buffer, event_buffer=event_buffer
        )

    active_games[game_id] = new_game
    return _build_state_payload(new_game, meta, logs=log_buffer, events=event_buffer)


@router.delete("/games/{game_id}")
@router.delete("/game/{game_id}", include_in_schema=False)
def delete_game(game_id: str):
    """Drop the active session and its metadata."""
    active_games.pop(game_id, None)
    game_meta.pop(game_id, None)
    return {"status": "deleted"}
