//! Unified live-game surface for debug, smoke-test, and forensic
//! workflows.
//!
//! `LiveGame` wraps a `Game` and exposes:
//! - **Four construction paths**: from decks (with seed), from
//!   hand-specified setup (DebugRunner-style), from a recording, or from
//!   a recording paused at a specific step.
//! - **Compact view accessors**: delegate to the `view::*` types so
//!   tool consumers (CLI, MCP) get token-efficient JSON.
//! - **Action methods**: thin wrappers over the public `Game` action
//!   surface, returning `ActionResult` with `events_emitted` /
//!   `pending_selection_after` so callers don't have to diff state by
//!   hand.
//!
//! The MCP server keeps a `HashMap<GameId, LiveGame>` in memory and
//! routes tool calls into the methods below. The CLI's REPL calls them
//! directly.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use serde::Serialize;
use serde_json::Value;

use crate::action::explain::{explain_action, legal_decoded_actions, ActionExplanation};
use crate::action::space::PASS;
use crate::card_data::CardData;
use crate::cards::build_registry;
use crate::debug_runner::{DebugRunner, DebugRunnerBuilder};
use crate::enums::{GamePhase, PlayerId};
use crate::events::GameEvent;
use crate::game::Game;
use crate::permanent::PermanentHandle;
use crate::rules::Rules;
use crate::runners::replay::{ReplayError, ReplayRunner};
use crate::view::{
    EffectQueueView, EventLogView, FieldView, HandView, ModifierView, PendingSelectionDebugView,
    Perspective, SecurityView, StateView,
};

/// Errors surfaced by `LiveGame::from_*` constructors.
#[derive(Debug)]
pub enum LiveGameError {
    /// Deck (or other zone) references card IDs not present in the loaded
    /// `card_data` pool. Listed so callers can suggest a wider pool.
    MissingCards(Vec<String>),
    /// `Game::new` rejected the construction (deck wrong size, etc).
    GameConstruction(String),
    /// Recording-specific failures bubbled up from `ReplayRunner`.
    Replay(ReplayError),
}

impl std::fmt::Display for LiveGameError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingCards(ids) => write!(f, "cards not in pool: {:?}", ids),
            Self::GameConstruction(s) => write!(f, "game construction failed: {}", s),
            Self::Replay(e) => write!(f, "replay error: {}", e),
        }
    }
}

impl std::error::Error for LiveGameError {}

impl From<ReplayError> for LiveGameError {
    fn from(e: ReplayError) -> Self {
        // Mirror the `MissingCards` story across error types so tool
        // consumers handle one shape regardless of construction path.
        match e {
            ReplayError::UnknownCard(ids) => LiveGameError::MissingCards(ids),
            other => LiveGameError::Replay(other),
        }
    }
}

/// Result of submitting an action to a `LiveGame`. Mirrors the spec's
/// `ActionResult` shape — never errors out of band, always returns a
/// structured outcome.
#[derive(Debug, Clone, Serialize)]
pub struct ActionResult {
    pub ok: bool,
    pub error: Option<String>,
    /// Events generated by this action, in emission order. Computed
    /// from the engine's monotonic `event_seq` counter (delta before/
    /// after the action). Each entry is a serialized `GameEvent` per
    /// `#[serde(tag = "type")]` — top-level `type` field plus
    /// variant-specific siblings, e.g.
    /// `{"type":"MemoryChange","seq":0,"player":0,"delta":-3,"total":-3}`.
    pub events_emitted: Vec<Value>,
    pub new_phase: String,
    pub pending_selection_after: Option<PendingSelectionDebugView>,
}

/// Target specifier for `LiveGame::attack`. Either an opponent
/// permanent (battle-attack) or the literal security stack
/// (security-attack).
#[derive(Debug, Clone, Copy)]
pub enum AttackTarget {
    Permanent(PermanentHandle),
    Security,
}

/// Lightweight card-inspection view. Returned by `LiveGame::inspect_card`.
#[derive(Debug, Clone, Serialize)]
pub struct CardInspection {
    pub card_id: String,
    pub card_name: String,
    pub card_kind: String,
    pub level: Option<u8>,
    pub dp: Option<i32>,
    pub play_cost: u16,
    pub colors: Vec<String>,
    pub traits: Vec<String>,
    pub effect_text: String,
    pub inherited_text: String,
    pub security_text: String,
    /// Whether this card has a registered Rust `CardEffect` impl. v1
    /// returns `true` for any card in the engine's effect registry
    /// (i.e. the same set `load_implemented_card_ids` returns).
    pub has_rust_effect: bool,
}

/// Per-card count entry in a `DeckCardsView`. Mirrors what an agent
/// would see if they cracked open the printed decklist: card metadata
/// plus how many copies of that card are in the deck.
#[derive(Debug, Clone, Serialize)]
pub struct DeckCardEntry {
    pub card_id: String,
    pub card_name: String,
    pub count: u16,
    pub card_kind: String,
    pub level: Option<u8>,
    pub dp: Option<i32>,
    pub play_cost: u16,
    pub colors: Vec<String>,
    pub traits: Vec<String>,
    pub effect_text: String,
    pub inherited_text: String,
    pub security_text: String,
    pub has_rust_effect: bool,
}

/// Both players' decks with full card metadata. Returned by
/// `LiveGame::deck_cards()`. Agents reading a recording or smoke-test
/// game cold use this to understand "what cards are in play" without
/// scanning `cards.json` separately.
#[derive(Debug, Clone, Serialize)]
pub struct DeckCardsView {
    pub deck1: Vec<DeckCardEntry>,
    pub deck2: Vec<DeckCardEntry>,
}

/// A single recorded action with its decoded label. Returned by
/// `LiveGame::recorded_actions(decode_labels: true)`.
#[derive(Debug, Clone, Serialize)]
pub struct RecordedActionView {
    pub step: u32,
    pub player_id: PlayerId,
    pub action_id: u16,
    pub phase: String,
    pub memory_before: i32,
    pub memory_after: i32,
    pub turn_number: u16,
    pub is_game_over: bool,
    pub winner_id: Option<PlayerId>,
    /// Decoded human-readable label for the action ID at the moment it
    /// was recorded (e.g. `"play hand[3]: Agumon"`). Only populated
    /// when `decode_labels: true`; otherwise `None`.
    pub label: Option<String>,
}

/// Unified live-game wrapper.
pub struct LiveGame {
    pub game: Game,
    /// Original deck card_ids per player. Retained at construction so
    /// `deck_cards()` can answer "what was in each deck" without
    /// dredging the engine's shuffled zones.
    deck_card_ids: [Vec<String>; 2],
    /// The recording JSON used to construct this game, if any. Held
    /// behind `Arc` so `recorded_actions()` can clone cheaply for the
    /// temporary replay-and-decode walk.
    recording: Option<Arc<Value>>,
}

impl LiveGame {
    // ── construction ─────────────────────────────────────────────────────

    /// Construct from two deck lists. Shuffles via the engine RNG; pass
    /// `seed = Some(s)` for deterministic shuffling.
    pub fn from_decks(
        deck1: Vec<String>,
        deck2: Vec<String>,
        seed: Option<u64>,
        card_data: &HashMap<String, CardData>,
    ) -> Result<Self, LiveGameError> {
        let mut missing: Vec<String> = Vec::new();
        for id in deck1.iter().chain(deck2.iter()) {
            if !card_data.contains_key(id) && !missing.iter().any(|m| m == id) {
                missing.push(id.clone());
            }
        }
        if !missing.is_empty() {
            return Err(LiveGameError::MissingCards(missing));
        }

        let decks = vec![deck1.clone(), deck2.clone()];
        let game = Game::new(&decks, card_data, Rules::standard(), seed)
            .map_err(LiveGameError::GameConstruction)?;
        Ok(Self {
            game,
            deck_card_ids: [deck1, deck2],
            recording: None,
        })
    }

    /// Construct from explicit zone configuration — mirrors the
    /// `DebugRunnerBuilder` path so debug sessions can start from a
    /// known mid-game shape without shuffling.
    ///
    /// `hands` and `decks` are maps from `PlayerId` to card_id lists.
    /// Missing entries become empty zones. `first_player` selects the
    /// turn order.
    pub fn from_debug(
        hands: HashMap<PlayerId, Vec<String>>,
        decks: HashMap<PlayerId, Vec<String>>,
        first_player: PlayerId,
        card_data: HashMap<String, CardData>,
    ) -> Result<Self, LiveGameError> {
        let mut missing: Vec<String> = Vec::new();
        for zone in hands.values().chain(decks.values()) {
            for id in zone {
                if !card_data.contains_key(id) && !missing.iter().any(|m| m == id) {
                    missing.push(id.clone());
                }
            }
        }
        if !missing.is_empty() {
            return Err(LiveGameError::MissingCards(missing));
        }

        let mut builder: DebugRunnerBuilder = DebugRunner::builder().with_card_data(card_data);
        for (pid, ids) in &hands {
            let refs: Vec<&str> = ids.iter().map(|s| s.as_str()).collect();
            builder = builder.hand(*pid, &refs);
        }
        for (pid, ids) in &decks {
            let refs: Vec<&str> = ids.iter().map(|s| s.as_str()).collect();
            builder = builder.deck(*pid, &refs);
        }
        let mut runner = builder.start();

        // DebugRunner doesn't directly expose a "first_player" setter; we
        // adjust turn_order after construction. The rotation puts
        // `first_player` at index 0 of turn_order.
        if let Some(pos) = runner
            .game
            .turn_order
            .iter()
            .position(|&p| p == first_player)
        {
            runner.game.turn_order.rotate_left(pos);
            runner.game.turn_player_idx = 0;
            if runner.game.turn_order.len() >= 2 {
                runner.game.memory_pair = (runner.game.turn_order[0], runner.game.turn_order[1]);
            }
        }

        // Reconstruct the per-player decklist from the union of hands +
        // decks. Debug games rarely populate security separately, but
        // when they do those cards are in their own zone — included for
        // completeness.
        let deck_card_ids = [
            collect_for_player(&hands, &decks, 0),
            collect_for_player(&hands, &decks, 1),
        ];
        Ok(Self {
            game: runner.game,
            deck_card_ids,
            recording: None,
        })
    }

    /// Construct from a recording (paused at step 0 — initial post-mulligan
    /// state, no actions applied).
    pub fn from_recording(
        recording: serde_json::Value,
        card_data: &HashMap<String, CardData>,
    ) -> Result<Self, LiveGameError> {
        let runner = ReplayRunner::new(recording.clone(), card_data, false)?;
        let deck_card_ids = deck_ids_from_recording(&recording);
        Ok(Self {
            game: runner.game,
            deck_card_ids,
            recording: Some(Arc::new(recording)),
        })
    }

    /// Construct from a recording, fast-forwarded to `step_n`.
    pub fn from_recording_at_step(
        recording: serde_json::Value,
        step_n: u32,
        card_data: &HashMap<String, CardData>,
    ) -> Result<Self, LiveGameError> {
        let mut runner = ReplayRunner::new(recording.clone(), card_data, false)?;
        runner.seek(step_n).map_err(LiveGameError::Replay)?;
        let deck_card_ids = deck_ids_from_recording(&recording);
        Ok(Self {
            game: runner.game,
            deck_card_ids,
            recording: Some(Arc::new(recording)),
        })
    }

    /// Wrap an already-constructed `Game` in a `LiveGame`. Used by
    /// callers (CLI verify mode, tests) that build a `Game` through a
    /// different path and want the view/action surface. Sets empty
    /// deck lists and no recording — `deck_cards()` returns empty
    /// vectors and `recorded_actions()` returns `None`.
    pub fn from_game(game: Game) -> Self {
        Self {
            game,
            deck_card_ids: [Vec::new(), Vec::new()],
            recording: None,
        }
    }

    /// Default card pool — the set of card IDs the engine has a
    /// registered `CardEffect` for. Mirrors `load_implemented_card_ids`
    /// in the PyO3 bindings, so the CLI / MCP defaults align with what
    /// `pilot_training`, `gauntlet`, and the architect agents use.
    pub fn default_pool() -> HashSet<String> {
        build_registry().registered_card_ids().into_iter().collect()
    }

    // ── view accessors ───────────────────────────────────────────────────

    pub fn state(&self, view: Perspective) -> StateView {
        StateView::from_game(&self.game, view)
    }

    pub fn hand(&self, player: PlayerId, view: Perspective) -> HandView {
        HandView::from_game(&self.game, player, view)
    }

    pub fn field(&self, player: PlayerId, view: Perspective) -> FieldView {
        FieldView::from_game(&self.game, player, view)
    }

    pub fn security(&self, player: PlayerId, view: Perspective) -> SecurityView {
        SecurityView::from_game(&self.game, player, view)
    }

    pub fn pending_selection(&self) -> Option<PendingSelectionDebugView> {
        self.game
            .pending_selection
            .as_ref()
            .map(|p| PendingSelectionDebugView::from_pending(&self.game, p))
    }

    pub fn effect_queue(&self) -> EffectQueueView {
        EffectQueueView::from_game(&self.game)
    }

    pub fn events(&self, since_seq: Option<u64>) -> EventLogView {
        EventLogView::from_game(&self.game, since_seq)
    }

    pub fn modifiers(&self, handle: PermanentHandle) -> ModifierView {
        ModifierView::from_game(&self.game, handle)
    }

    /// Decoded list of every action ID currently legal for `player`.
    ///
    /// Returns an empty `Vec` when `player != current_decision_player()`.
    /// The debug surface guarantees that returned actions are
    /// `step`-executable at the moment of the call — callers will not see
    /// phantom actions for inactive players (which would silently no-op
    /// through `Game::decode_action`).
    pub fn legal_actions(&self, player: PlayerId) -> Vec<ActionExplanation> {
        if player != self.current_decision_player() {
            return Vec::new();
        }
        legal_decoded_actions(&self.game, player)
    }

    pub fn inspect_card(&self, card_id: &str) -> Option<CardInspection> {
        let cd = self.game.card_data.iter().find(|c| c.card_id == card_id)?;
        let has_rust_effect = self.game.effect_registry.get(card_id).is_some();
        Some(CardInspection {
            card_id: cd.card_id.clone(),
            card_name: cd.card_name.clone(),
            card_kind: format!("{:?}", cd.card_kind),
            level: cd.level,
            dp: cd.dp,
            play_cost: cd.play_cost,
            colors: cd.colors.iter().map(|c| format!("{:?}", c)).collect(),
            traits: cd.traits.clone(),
            effect_text: cd.effect_text.clone(),
            inherited_text: cd.inherited_text.clone(),
            security_text: cd.security_text.clone(),
            has_rust_effect,
        })
    }

    /// Return the full deck contents (card metadata + per-card counts)
    /// for both players. Lets agents reading a recording or smoke-test
    /// game cold ask "what cards are in play" in one tool call.
    ///
    /// Cards that were referenced by the original deck but aren't in
    /// the engine's loaded `card_data` are silently skipped — should
    /// never happen because construction validates against the pool.
    pub fn deck_cards(&self) -> DeckCardsView {
        DeckCardsView {
            deck1: self.deck_entries(0),
            deck2: self.deck_entries(1),
        }
    }

    fn deck_entries(&self, player_idx: usize) -> Vec<DeckCardEntry> {
        let ids = self
            .deck_card_ids
            .get(player_idx)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        let mut counts: std::collections::BTreeMap<&str, u16> = std::collections::BTreeMap::new();
        for id in ids {
            *counts.entry(id.as_str()).or_insert(0) += 1;
        }
        let cd_index: HashMap<&str, &CardData> = self
            .game
            .card_data
            .iter()
            .map(|cd| (cd.card_id.as_str(), cd))
            .collect();
        counts
            .into_iter()
            .filter_map(|(card_id, count)| {
                let cd = cd_index.get(card_id)?;
                Some(DeckCardEntry {
                    card_id: cd.card_id.clone(),
                    card_name: cd.card_name.clone(),
                    count,
                    card_kind: format!("{:?}", cd.card_kind),
                    level: cd.level,
                    dp: cd.dp,
                    play_cost: cd.play_cost,
                    colors: cd.colors.iter().map(|c| format!("{:?}", c)).collect(),
                    traits: cd.traits.clone(),
                    effect_text: cd.effect_text.clone(),
                    inherited_text: cd.inherited_text.clone(),
                    security_text: cd.security_text.clone(),
                    has_rust_effect: self.game.effect_registry.get(&cd.card_id).is_some(),
                })
            })
            .collect()
    }

    /// Whether this game was constructed from a recording (i.e. has a
    /// recorded action log to replay).
    pub fn has_recording(&self) -> bool {
        self.recording.is_some()
    }

    /// Return the recorded action log. With `decode_labels: true`, every
    /// entry's `label` is populated with the human-readable decoded
    /// action string at the *recording-time* engine context — produced
    /// by spinning up a fresh temporary `ReplayRunner`, walking step by
    /// step, and calling `explain_action` *before* each step is applied.
    ///
    /// With `decode_labels: false` (or for games not constructed from a
    /// recording), labels are `None`.
    ///
    /// Returns `None` when the live game wasn't built from a recording.
    pub fn recorded_actions(&self, decode_labels: bool) -> Option<Vec<RecordedActionView>> {
        let recording = self.recording.as_ref()?.clone();
        let actions = recording.get("actions")?.as_array()?;

        let labels: Vec<Option<String>> = if decode_labels {
            let card_data_map: HashMap<String, CardData> = self
                .game
                .card_data
                .iter()
                .map(|cd| (cd.card_id.clone(), cd.clone()))
                .collect();
            decode_labels_via_replay((*recording).clone(), &card_data_map, actions.len())
        } else {
            vec![None; actions.len()]
        };

        let out: Vec<RecordedActionView> = actions
            .iter()
            .enumerate()
            .map(|(idx, a)| RecordedActionView {
                step: a.get("step").and_then(|v| v.as_u64()).unwrap_or(0) as u32,
                player_id: (a
                    .get("player_id")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(1)
                    .saturating_sub(1)) as PlayerId,
                action_id: a.get("action_id").and_then(|v| v.as_u64()).unwrap_or(0) as u16,
                phase: a
                    .get("phase")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string(),
                memory_before: a.get("memory_before").and_then(|v| v.as_i64()).unwrap_or(0) as i32,
                memory_after: a.get("memory_after").and_then(|v| v.as_i64()).unwrap_or(0) as i32,
                turn_number: a.get("turn").and_then(|v| v.as_u64()).unwrap_or(0) as u16,
                is_game_over: a
                    .get("is_game_over")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false),
                winner_id: a
                    .get("winner_id")
                    .and_then(|v| v.as_u64())
                    .map(|x| x.saturating_sub(1) as PlayerId),
                label: labels.get(idx).cloned().unwrap_or(None),
            })
            .collect();
        Some(out)
    }

    // ── action methods ───────────────────────────────────────────────────

    /// Player whose decision is currently expected. Drives mulligan,
    /// selection resolution, and turn-player actions. Matches
    /// `HeadlessRunner::current_decision_player`.
    pub fn current_decision_player(&self) -> PlayerId {
        if let Some(p) = self.game.mulligan_current_player() {
            return p;
        }
        if let Some(sel) = self.game.pending_selection.as_ref() {
            return sel.selecting_player;
        }
        self.game.turn_player()
    }

    /// Submit a raw action ID through the engine's decoder.
    ///
    /// This intentionally diverges from `HeadlessRunner::step` (which is
    /// fire-and-forget for the RL training pipeline). The debug surface
    /// validates: if the engine's `decode_action` results in no state
    /// change and no events (i.e., the action was silently dropped),
    /// `step` returns `ok: false` with a descriptive error so callers
    /// can detect failed actions.
    ///
    /// As a safety net for mandatory pending selections whose only legal
    /// option is unfulfillable (install-time filter admitted a target
    /// but the resulting callback no-ops), `step` automatically fizzles
    /// the pending selection — clears it, restores the previous phase,
    /// emits a `GameEvent::EffectFizzled`, and returns `ok: true`. This
    /// matches the engine's existing fizzle-on-empty convention at
    /// install time (`selections.rs:install_field_selection`).
    pub fn step(&mut self, action_id: u16) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        let pid = self.current_decision_player();

        // Snapshot for no-op detection. Pending-selection identity is
        // tracked by `(prompt, options, source)` because the engine
        // mutates `pending_selection` in place when partially-consumed.
        let before_seq = self.game.event_seq;
        let before_phase = self.game.current_phase;
        let before_pending = self
            .game
            .pending_selection
            .as_ref()
            .map(pending_fingerprint);

        // For fizzle detection we need to know whether this was the only
        // legal option for a mandatory pending BEFORE dispatching.
        let fizzle_candidate = self
            .game
            .pending_selection
            .as_ref()
            .filter(|sel| !sel.is_optional && sel.valid_action_ids.len() == 1)
            .map(|sel| (sel.previous_phase, sel.source_permanent));

        self.game.decode_action(action_id, pid);

        let after_seq = self.game.event_seq;
        let after_phase = self.game.current_phase;
        let after_pending = self
            .game
            .pending_selection
            .as_ref()
            .map(pending_fingerprint);

        let advanced = after_seq != before_seq
            || after_phase != before_phase
            || after_pending != before_pending;

        if !advanced {
            // Engine rejected the action. If we were in a mandatory
            // pending with a single unfulfillable option, fizzle.
            if let Some((previous_phase, source_permanent)) = fizzle_candidate {
                self.game.pending_selection = None;
                self.game.current_phase = previous_phase;
                let seq = self.game.next_event_seq();
                self.game.events.push(GameEvent::EffectFizzled {
                    seq,
                    source_permanent,
                    reason: "no executable target".into(),
                });
                return self.make_result(true, None, before_seq);
            }
            return self.make_result(
                false,
                Some(format!(
                    "action {} not legal for player {} in phase {:?}",
                    action_id, pid, before_phase
                )),
                before_seq,
            );
        }
        self.make_result(true, None, before_seq)
    }

    /// Play a card from the given player's hand via the public Game
    /// surface.
    ///
    /// The wrapper enforces:
    /// - `current_decision_player() == player` (rejects out-of-turn plays)
    /// - `current_phase == GamePhase::Main` (rejects Mulligan, selection
    ///   phases, combat timings, etc. — Counter-window Option plays use
    ///   `step` with a separate action-ID range, not `play()`)
    /// - hand_idx is within bounds
    /// - the underlying `Game::play_from_hand` accepts (memory, field
    ///   capacity, play blockers)
    ///
    /// `Game::play_from_hand` itself does NOT validate phase — the
    /// wrapper is the sole enforcement point.
    pub fn play(&mut self, player: PlayerId, hand_idx: usize) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        if self.current_decision_player() != player {
            return self.make_result(
                false,
                Some(format!(
                    "play rejected: player {} is not the current decision player ({})",
                    player,
                    self.current_decision_player()
                )),
                self.game.event_seq,
            );
        }
        if self.game.current_phase != GamePhase::Main {
            return self.make_result(
                false,
                Some(format!(
                    "play rejected: current phase is {:?}, play requires Main",
                    self.game.current_phase
                )),
                self.game.event_seq,
            );
        }
        if hand_idx >= self.game.player(player).hand.len() {
            return self.make_result(
                false,
                Some(format!(
                    "hand index {} out of range (hand size = {})",
                    hand_idx,
                    self.game.player(player).hand.len()
                )),
                self.game.event_seq,
            );
        }
        let before_seq = self.game.event_seq;
        let placed = self.game.play_from_hand(player, hand_idx);
        let ok = placed.is_some();
        let error = if ok {
            None
        } else {
            Some("play_from_hand rejected: insufficient memory, field full, or play blocked".into())
        };
        self.make_result(ok, error, before_seq)
    }

    /// Resolve the current pending selection by submitting an action ID.
    pub fn resolve_selection(&mut self, player: PlayerId, action_id: u16) -> ActionResult {
        if self.game.pending_selection.is_none() {
            return self.make_result(
                false,
                Some("no pending selection".into()),
                self.game.event_seq,
            );
        }
        let before_seq = self.game.event_seq;
        match self.game.resolve_selection(player, action_id) {
            Ok(_) => self.make_result(true, None, before_seq),
            Err(_) => self.make_result(
                false,
                Some("selection rejected: invalid choice for current prompt".into()),
                before_seq,
            ),
        }
    }

    /// End the current turn.
    ///
    /// Accepts only when `current_phase ∈ { Main, EndOfTurnAction }`.
    /// `Game::end_turn` forcibly sets the phase to `EndTurn` regardless
    /// of starting phase — calling it during Mulligan would corrupt
    /// state, so the wrapper rejects all other phases.
    pub fn end_turn(&mut self) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        if !matches!(
            self.game.current_phase,
            GamePhase::Main | GamePhase::EndOfTurnAction
        ) {
            return self.make_result(
                false,
                Some(format!(
                    "end_turn rejected: current phase is {:?}, end_turn requires Main or EndOfTurnAction",
                    self.game.current_phase
                )),
                self.game.event_seq,
            );
        }
        let before_seq = self.game.event_seq;
        self.game.end_turn();
        self.make_result(true, None, before_seq)
    }

    /// Pass / advance the active phase.
    ///
    /// Accepts when `current_phase ∈ { Breeding, Main, EndOfTurnAction }`.
    /// These are the phases where the engine's decoder accepts `PASS`.
    /// Selection phases, combat timings, Mulligan, and game-over are
    /// rejected with a structured error.
    pub fn pass_turn(&mut self) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        if !matches!(
            self.game.current_phase,
            GamePhase::Breeding | GamePhase::Main | GamePhase::EndOfTurnAction
        ) {
            return self.make_result(
                false,
                Some(format!(
                    "pass_turn rejected: current phase is {:?}, pass_turn requires Breeding, Main, or EndOfTurnAction",
                    self.game.current_phase
                )),
                self.game.event_seq,
            );
        }
        let pid = self.current_decision_player();
        let before_seq = self.game.event_seq;
        self.game.decode_action(PASS, pid);
        self.make_result(true, None, before_seq)
    }

    /// Move the breeding-area permanent to the battle area.
    pub fn move_from_breeding(&mut self, player: PlayerId) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        let before_seq = self.game.event_seq;
        let moved = self.game.move_from_breeding(player);
        let error = if moved {
            None
        } else {
            Some("move_from_breeding rejected: no carrier or breeding not legal".into())
        };
        self.make_result(moved, error, before_seq)
    }

    /// Digivolve a card from hand onto an existing permanent.
    ///
    /// Resolves the typed arguments to an action ID via
    /// `legal_decoded_actions`, then dispatches through `step` (which
    /// applies the same validation: phase check, no-op detection, fizzle).
    ///
    /// `host` is the permanent being digivolved onto — must belong to the
    /// active player. `source_hand_idx` is the digivolution-source card
    /// in the active player's hand.
    pub fn digivolve(&mut self, host: PermanentHandle, source_hand_idx: usize) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        let pid = self.current_decision_player();
        if host.player != pid {
            return self.make_result(
                false,
                Some(format!(
                    "digivolve rejected: host belongs to player {} but current decision player is {}",
                    host.player, pid
                )),
                self.game.event_seq,
            );
        }
        // Find the matching legal action.
        let acts = legal_decoded_actions(&self.game, pid);
        let matching = acts.iter().find(|a| {
            a.kind == crate::action::explain::ActionKind::Digivolve
                && a.source_zone == Some(crate::action::explain::ActionZone::Hand)
                && a.source_index == Some(source_hand_idx as u16)
                && a.target_index == Some(host.index as u16)
        });
        let Some(action) = matching else {
            return self.make_result(
                false,
                Some(format!(
                    "digivolve rejected: no legal digivolve action for host {:?} from hand[{}]",
                    host, source_hand_idx
                )),
                self.game.event_seq,
            );
        };
        let action_id = action.action_id;
        self.step(action_id)
    }

    /// Declare an attack from `attacker` against `target`.
    ///
    /// `target` is either a permanent handle (battle-attack against an
    /// opponent Digimon) or `AttackTarget::Security` (security-attack).
    /// Resolves to an action ID via `legal_decoded_actions` then
    /// dispatches through `step`.
    pub fn attack(&mut self, attacker: PermanentHandle, target: AttackTarget) -> ActionResult {
        if self.game.game_over {
            return self.make_result(false, Some("game is over".into()), 0);
        }
        let pid = self.current_decision_player();
        if attacker.player != pid {
            return self.make_result(
                false,
                Some(format!(
                    "attack rejected: attacker belongs to player {} but current decision player is {}",
                    attacker.player, pid
                )),
                self.game.event_seq,
            );
        }
        let acts = legal_decoded_actions(&self.game, pid);
        let matching = acts.iter().find(|a| {
            if a.kind != crate::action::explain::ActionKind::Attack {
                return false;
            }
            if a.source_index != Some(attacker.index as u16) {
                return false;
            }
            match target {
                AttackTarget::Security => {
                    a.target_zone == Some(crate::action::explain::ActionZone::Security)
                }
                AttackTarget::Permanent(t) => {
                    a.target_zone == Some(crate::action::explain::ActionZone::Battle)
                        && a.target_index == Some(t.index as u16)
                }
            }
        });
        let Some(action) = matching else {
            return self.make_result(
                false,
                Some(format!(
                    "attack rejected: no legal attack action for attacker {:?} against {:?}",
                    attacker, target
                )),
                self.game.event_seq,
            );
        };
        let action_id = action.action_id;
        self.step(action_id)
    }

    // ── internals ────────────────────────────────────────────────────────

    fn make_result(&self, ok: bool, error: Option<String>, before_seq: u64) -> ActionResult {
        // Serialize each event via serde — fall back to a structured
        // error wrapper only if serialization ever fails (shouldn't,
        // given the GameEvent derive). Using `Value` so callers receive
        // structured objects with `type` + variant-specific fields.
        let events_emitted: Vec<Value> = events_since(&self.game, before_seq)
            .map(|e| {
                serde_json::to_value(e).unwrap_or_else(|err| {
                    serde_json::json!({
                        "type": "SerializationError",
                        "error": err.to_string(),
                        "debug": format!("{:?}", e),
                    })
                })
            })
            .collect();
        let new_phase = format!("{:?}", self.game.current_phase);
        let pending_selection_after = self.pending_selection();
        ActionResult {
            ok,
            error,
            events_emitted,
            new_phase,
            pending_selection_after,
        }
    }
}

/// Compact stable identity for a pending selection. Used by
/// `LiveGame::step` to detect whether `decode_action` advanced the
/// pending state (e.g. mid-selection pick that doesn't change phase or
/// event_seq but does shrink `valid_action_ids`).
fn pending_fingerprint(sel: &crate::selection::PendingSelection) -> PendingFingerprint {
    PendingFingerprint {
        prompt: sel.prompt.clone(),
        kind_debug: format!("{:?}", sel.kind),
        valid_action_ids: sel.valid_action_ids.clone(),
        is_optional: sel.is_optional,
        source_permanent: sel.source_permanent,
    }
}

#[derive(PartialEq, Eq)]
struct PendingFingerprint {
    prompt: String,
    kind_debug: String,
    valid_action_ids: Vec<u16>,
    is_optional: bool,
    source_permanent: Option<PermanentHandle>,
}

/// Return an iterator over events generated after `before_seq`. The
/// `event_seq` counter is monotonic; each emitted event corresponds to
/// the seq value at emission time, and the `events` Vec preserves
/// chronological order. We use the seq delta to slice from the tail.
fn events_since(game: &Game, before_seq: u64) -> impl Iterator<Item = &GameEvent> {
    let total = game.event_seq;
    let delta = total.saturating_sub(before_seq) as usize;
    let len = game.events.len();
    let start = len.saturating_sub(delta);
    game.events[start..].iter()
}

// ── unused-import suppressors (referenced by spec extension points) ──────
#[allow(dead_code)]
fn _phase_witness() {
    let _ = std::any::type_name::<GamePhase>();
}

/// Combine a player's hand + deck (from `from_debug`) into a single
/// card_id list. Cards not assigned to a player land in player 0's
/// list by default; the spec for `from_debug` doesn't pin behavior on
/// missing keys.
fn collect_for_player(
    hands: &HashMap<PlayerId, Vec<String>>,
    decks: &HashMap<PlayerId, Vec<String>>,
    player: PlayerId,
) -> Vec<String> {
    let mut ids: Vec<String> = Vec::new();
    if let Some(h) = hands.get(&player) {
        ids.extend(h.iter().cloned());
    }
    if let Some(d) = decks.get(&player) {
        ids.extend(d.iter().cloned());
    }
    ids
}

/// Derive `[deck1_ids, deck2_ids]` from a recording's `initial_state`.
/// Concatenates library + hand + security + digitama for each player
/// since those zones together cover the post-shuffle deck (pre-shuffle
/// `deck_list` may be empty on older recordings).
fn deck_ids_from_recording(recording: &Value) -> [Vec<String>; 2] {
    let initial = recording.get("initial_state");
    [
        collect_player_ids_from_recording(initial, "player1"),
        collect_player_ids_from_recording(initial, "player2"),
    ]
}

fn collect_player_ids_from_recording(initial: Option<&Value>, key: &str) -> Vec<String> {
    let Some(p) = initial.and_then(|i| i.get(key)) else {
        return Vec::new();
    };
    // Prefer the pre-shuffle deck_list when present (more authoritative).
    if let Some(arr) = p.get("deck_list").and_then(|v| v.as_array()) {
        let ids: Vec<String> = arr
            .iter()
            .filter_map(|v| v.as_str().map(String::from))
            .collect();
        if !ids.is_empty() {
            return ids;
        }
    }
    // Fallback: union of post-shuffle zones (these together = the deck).
    let mut ids: Vec<String> = Vec::new();
    for zone in &[
        "library_order",
        "initial_hand",
        "security_order",
        "digitama_library_order",
    ] {
        if let Some(arr) = p.get(zone).and_then(|v| v.as_array()) {
            for v in arr {
                if let Some(s) = v.as_str() {
                    ids.push(s.to_string());
                }
            }
        }
    }
    ids
}

/// Spin up a temporary `ReplayRunner` from `recording` and walk every
/// action in the action log, calling `explain_action` *before* each
/// step is applied to capture the action's label in its recording-time
/// engine context. Returns one `Option<String>` per recorded action;
/// mulligan-phase actions (which `ReplayRunner` filters from its
/// step stream) get labels via direct `explain_action` against the
/// fresh post-construction game.
///
/// `total_actions` is the size of the recording's `actions` array;
/// the returned vec has exactly that length.
fn decode_labels_via_replay(
    recording: Value,
    card_data: &HashMap<String, CardData>,
    total_actions: usize,
) -> Vec<Option<String>> {
    let mut labels: Vec<Option<String>> = vec![None; total_actions];

    // We need labels for every recorded action, including the mulligan
    // ones the runner filters from its step stream. Construct a fresh
    // ReplayRunner — it lands post-mulligan in turn 1.
    let Ok(mut runner) = ReplayRunner::new(recording.clone(), card_data, false) else {
        return labels;
    };

    // Mulligan-phase labels are deterministic: action_id 0 = "keep",
    // action_id 1 = "redraw". Decode from the recording's action array
    // directly without needing engine state.
    let Some(actions) = recording.get("actions").and_then(|v| v.as_array()) else {
        return labels;
    };

    // Phase-1: assign labels to mulligan actions.
    for (idx, a) in actions.iter().enumerate() {
        if a.get("phase").and_then(|v| v.as_str()) == Some("Mulligan") {
            let action_id = a.get("action_id").and_then(|v| v.as_u64()).unwrap_or(0);
            labels[idx] = Some(match action_id {
                0 => "mulligan: keep".to_string(),
                1 => "mulligan: redraw".to_string(),
                other => format!("mulligan: unknown ({})", other),
            });
        }
    }

    // Phase-2: walk replayable (non-mulligan) actions, capturing the
    // label BEFORE each step is applied. Map each replayable step back
    // to its original index in `actions`.
    let non_mull_indices: Vec<usize> = actions
        .iter()
        .enumerate()
        .filter(|(_, a)| a.get("phase").and_then(|v| v.as_str()) != Some("Mulligan"))
        .map(|(i, _)| i)
        .collect();
    for (step_idx, orig_idx) in non_mull_indices.iter().enumerate() {
        if step_idx >= runner.total_steps() as usize {
            break;
        }
        let a = &actions[*orig_idx];
        let action_id = a.get("action_id").and_then(|v| v.as_u64()).unwrap_or(0) as u16;
        let recorded_player_py = a.get("player_id").and_then(|v| v.as_u64()).unwrap_or(1) as u8;
        let player_id: PlayerId = recorded_player_py.saturating_sub(1);
        let explanation = explain_action(&runner.game, player_id, action_id);
        labels[*orig_idx] = Some(explanation.label);
        runner.step();
    }

    labels
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::card_data::CardData;

    fn minimal_db() -> HashMap<String, CardData> {
        let json = r#"{
            "ST1-01": {
                "card_id": "ST1-01", "card_name_eng": "Botamon",
                "card_effect_class_name": "ST1_01", "play_cost": 0, "dp": -1,
                "level": 2, "card_kind": 3, "rarity": 0, "card_colors": [0],
                "type_eng": ["Lesser"], "form_eng": ["In-Training"], "attribute_eng": [],
                "effect_description_eng": "", "inherited_effect_description_eng": "",
                "security_effect_description_eng": "", "evo_costs": []
            },
            "ST1-03": {
                "card_id": "ST1-03", "card_name_eng": "Koromon",
                "card_effect_class_name": "ST1_03", "play_cost": 3, "dp": 2000,
                "level": 3, "card_kind": 0, "rarity": 0, "card_colors": [0],
                "type_eng": ["Lesser"], "form_eng": ["Rookie"], "attribute_eng": ["Free"],
                "effect_description_eng": "", "inherited_effect_description_eng": "",
                "security_effect_description_eng": "", "evo_costs": []
            }
        }"#;
        CardData::load_from_str(json).unwrap()
    }

    fn small_deck() -> Vec<String> {
        std::iter::repeat("ST1-01".to_string())
            .take(5)
            .chain(std::iter::repeat("ST1-03".to_string()).take(45))
            .collect()
    }

    #[test]
    fn from_decks_constructs_in_mulligan() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(7), &db)
            .expect("from_decks succeeds");
        assert_eq!(lg.game.current_phase, GamePhase::Mulligan);
    }

    #[test]
    fn from_decks_missing_card_reports_offender() {
        let db = minimal_db();
        let bad_deck = std::iter::repeat("UNKNOWN-X".to_string())
            .take(50)
            .collect();
        match LiveGame::from_decks(bad_deck, small_deck(), None, &db) {
            Err(LiveGameError::MissingCards(ids)) => {
                assert!(ids.contains(&"UNKNOWN-X".to_string()));
            }
            other => panic!("expected MissingCards, got {:?}", other.err()),
        }
    }

    #[test]
    fn default_pool_is_nonempty() {
        let pool = LiveGame::default_pool();
        // Engine registers at least the TEST cards (cards/test_cards.rs).
        assert!(
            !pool.is_empty(),
            "default_pool is empty — engine registry has no cards?"
        );
    }

    #[test]
    fn state_view_god_perspective_works() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let st = lg.state(Perspective::God);
        assert_eq!(st.phase, "Mulligan");
        assert!(!st.game_over);
    }

    #[test]
    fn legal_actions_in_mulligan_lists_keep_and_redraw() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let player = lg.current_decision_player();
        let actions = lg.legal_actions(player);
        // Mulligan mask should set bits 0 (keep) and 1 (redraw).
        let ids: Vec<u16> = actions.iter().map(|a| a.action_id).collect();
        assert!(ids.contains(&0));
        assert!(ids.contains(&1));
    }

    // ── Validation regression tests (enforce-live-game-action-contracts) ───

    #[test]
    fn step_with_illegal_action_id_returns_ok_false() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        // During Mulligan, only action_ids 0 and 1 are legal. action_id 9999
        // is not in the legal set for any phase — must be rejected with
        // ok:false and an error naming the action_id.
        let r = lg.step(9999);
        assert!(!r.ok, "step(9999) during Mulligan should return ok:false");
        let err = r.error.expect("error message present");
        assert!(
            err.contains("9999"),
            "error should name the action_id: {}",
            err
        );
    }

    #[test]
    fn play_during_mulligan_returns_ok_false() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let phase_before = lg.game.current_phase;
        // Call play with the CURRENT mulligan player so the phase check
        // (not the decision-player check) is the one that fires.
        let active = lg.current_decision_player();
        let r = lg.play(active, 0);
        assert!(!r.ok, "play during Mulligan should return ok:false");
        let err = r.error.expect("error message present");
        assert!(
            err.contains("Mulligan") || err.contains("Main") || err.contains("phase"),
            "error should mention phase mismatch: {}",
            err
        );
        assert_eq!(lg.game.current_phase, phase_before, "phase unchanged");
    }

    #[test]
    fn play_out_of_turn_returns_ok_false() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        // Advance through mulligan and to Main phase.
        let _ = lg.step(0); // P? keep
        let _ = lg.step(0); // P? keep
                            // Now T1 Breeding. Pass to reach Main.
        let _ = lg.pass_turn(); // Breeding → (hatch or Main); test by passing.
                                // At this point the engine is in Main for SOME player. We test that
                                // the OTHER player cannot play.
        let active = lg.current_decision_player();
        let other = 1 - active;
        let phase_before = lg.game.current_phase;
        let r = lg.play(other, 0);
        assert!(
            !r.ok,
            "play by non-active player should be rejected (active={}, attempted={})",
            active, other
        );
        let err = r.error.expect("error message present");
        assert!(
            err.contains("decision player"),
            "error should mention decision player mismatch: {}",
            err
        );
        assert_eq!(lg.game.current_phase, phase_before, "phase unchanged");
    }

    #[test]
    fn end_turn_during_mulligan_returns_ok_false_no_state_change() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let phase_before = lg.game.current_phase;
        let turn_before = lg.game.turn_count;
        let r = lg.end_turn();
        assert!(!r.ok, "end_turn during Mulligan must be rejected");
        assert_eq!(lg.game.current_phase, phase_before, "phase must not change");
        assert_eq!(
            lg.game.turn_count, turn_before,
            "turn_count must not change"
        );
    }

    #[test]
    fn pass_turn_during_mulligan_returns_ok_false() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let phase_before = lg.game.current_phase;
        let r = lg.pass_turn();
        assert!(!r.ok, "pass_turn during Mulligan must be rejected");
        assert_eq!(lg.game.current_phase, phase_before);
    }

    #[test]
    fn legal_actions_for_non_decision_player_returns_empty() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let active = lg.current_decision_player();
        let other = 1 - active;
        let acts_active = lg.legal_actions(active);
        let acts_other = lg.legal_actions(other);
        assert!(
            !acts_active.is_empty(),
            "active player should have legal actions during Mulligan"
        );
        assert!(
            acts_other.is_empty(),
            "non-decision player should have NO legal actions; got {} entries",
            acts_other.len()
        );
    }

    #[test]
    fn events_emitted_is_structured_json_not_debug_string() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        // Drive into Main and play a card to fire MemoryChange + Play events.
        let _ = lg.step(0); // mulligan keep
        let _ = lg.step(0); // mulligan keep
        let _ = lg.pass_turn(); // Breeding -> Main
        let active = lg.current_decision_player();
        // Memory at start of T1 for second player is 3; Koromon costs 3.
        // If active player has Koromon at hand[0] and enough memory, play
        // succeeds and emits MemoryChange + Play events.
        if lg.game.memory < 3 && active == lg.game.turn_player() {
            // Insufficient memory for first player; pass to flip to opp.
            let _ = lg.pass_turn();
        }
        let r = lg.play(lg.current_decision_player(), 0);
        // Whether play succeeds or fails, events_emitted is now a
        // Vec<Value> not Vec<String>. Verify by serializing.
        let v = serde_json::to_value(&r).unwrap();
        let evs = v["events_emitted"]
            .as_array()
            .expect("events_emitted is array");
        for ev in evs {
            assert!(
                ev.is_object(),
                "each event must be a structured object, got {:?}",
                ev
            );
            assert!(
                ev.get("type").and_then(|x| x.as_str()).is_some(),
                "each event must have a string `type` field: {:?}",
                ev
            );
        }
    }

    #[test]
    fn game_event_serializes_with_type_tag() {
        // Construct sample GameEvent variants and verify the wire shape.
        let ev = GameEvent::MemoryChange {
            seq: 7,
            player: 0,
            delta: -3,
            total: -3,
        };
        let v = serde_json::to_value(&ev).unwrap();
        assert_eq!(v["type"], "MemoryChange");
        assert_eq!(v["seq"], 7);
        assert_eq!(v["player"], 0);
        assert_eq!(v["delta"], -3);
        assert_eq!(v["total"], -3);

        let ev = GameEvent::Play {
            seq: 8,
            player: 0,
            card_id: "BT24-008".into(),
            field_index: 0,
        };
        let v = serde_json::to_value(&ev).unwrap();
        assert_eq!(v["type"], "Play");
        assert_eq!(v["card_id"], "BT24-008");

        let ev = GameEvent::GameOver {
            seq: 22,
            winner: Some(0),
            reason: crate::game::TerminalOutcomeReason::SecurityAttack,
        };
        let v = serde_json::to_value(&ev).unwrap();
        assert_eq!(v["type"], "GameOver");
        assert_eq!(v["winner"], 0);
        assert_eq!(v["reason"], "SecurityAttack");

        let ev = GameEvent::EffectFizzled {
            seq: 50,
            source_permanent: Some(PermanentHandle {
                player: 0,
                index: 1,
            }),
            reason: "no executable target".into(),
        };
        let v = serde_json::to_value(&ev).unwrap();
        assert_eq!(v["type"], "EffectFizzled");
        assert_eq!(v["reason"], "no executable target");
        assert_eq!(v["source_permanent"]["player"], 0);
        assert_eq!(v["source_permanent"]["index"], 1);
    }

    #[test]
    fn pass_turn_succeeds_post_mulligan() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        // Mulligan both keep. Post-mulligan phase is Breeding (the engine
        // parks here on turn 1 to allow Hatch). pass_turn dispatches PASS,
        // which the breeding-phase decoder accepts as "advance to Main".
        let _ = lg.step(0);
        let _ = lg.step(0);
        let r = lg.pass_turn();
        assert!(
            r.ok,
            "pass_turn should succeed in any non-terminal phase, got {:?}",
            r
        );
    }

    #[test]
    fn illegal_play_returns_structured_error_no_state_change() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let _ = lg.step(0);
        let _ = lg.step(0);
        let phase_before = lg.game.current_phase;
        let memory_before = lg.game.memory;
        // Hand index 99 is out of range.
        let r = lg.play(0, 99);
        assert!(!r.ok);
        assert!(r.error.is_some());
        // Engine state unchanged.
        assert_eq!(lg.game.current_phase, phase_before);
        assert_eq!(lg.game.memory, memory_before);
    }

    #[test]
    fn resolve_selection_when_none_pending_returns_error() {
        let db = minimal_db();
        let mut lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        // Get into a state without a pending selection.
        let _ = lg.step(0);
        let _ = lg.step(0);
        let r = lg.resolve_selection(0, 0);
        assert!(!r.ok);
        assert!(r.error.as_deref().unwrap_or("").contains("no pending"));
    }

    #[test]
    fn inspect_card_returns_metadata_for_loaded_card() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let ins = lg.inspect_card("ST1-03").expect("ST1-03 is in pool");
        assert_eq!(ins.card_id, "ST1-03");
        assert_eq!(ins.card_name, "Koromon");
    }

    #[test]
    fn inspect_card_returns_none_for_unknown() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        assert!(lg.inspect_card("UNKNOWN-XYZ").is_none());
    }

    #[test]
    fn action_result_serializes() {
        let r = ActionResult {
            ok: true,
            error: None,
            events_emitted: vec![
                serde_json::json!({"type": "MemoryChange", "seq": 0}),
                serde_json::json!({"type": "Play", "seq": 1}),
            ],
            new_phase: "Main".into(),
            pending_selection_after: None,
        };
        let json = serde_json::to_value(&r).unwrap();
        assert_eq!(json["ok"], true);
        assert_eq!(json["events_emitted"].as_array().unwrap().len(), 2);
        assert_eq!(json["events_emitted"][0]["type"], "MemoryChange");
    }

    #[test]
    fn from_debug_with_explicit_hands() {
        let db = minimal_db();
        let mut hands = HashMap::new();
        hands.insert(0u8, vec!["ST1-03".to_string()]);
        hands.insert(1u8, vec!["ST1-03".to_string()]);
        let mut decks = HashMap::new();
        decks.insert(0u8, vec!["ST1-03".to_string(); 30]);
        decks.insert(1u8, vec!["ST1-03".to_string(); 30]);
        let lg = LiveGame::from_debug(hands, decks, 0, db).expect("debug build");
        assert_eq!(lg.game.players[0].hand.len(), 1);
        assert_eq!(lg.game.players[0].deck.len(), 30);
        assert_eq!(lg.game.turn_player(), 0);
    }

    #[test]
    fn deck_cards_from_decks_returns_unique_with_counts() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let dc = lg.deck_cards();
        // 5 eggs (ST1-01) + 45 main (ST1-03) per player.
        let p1_st01 = dc
            .deck1
            .iter()
            .find(|e| e.card_id == "ST1-01")
            .expect("ST1-01 present");
        assert_eq!(p1_st01.count, 5);
        let p1_st03 = dc
            .deck1
            .iter()
            .find(|e| e.card_id == "ST1-03")
            .expect("ST1-03 present");
        assert_eq!(p1_st03.count, 45);
        // Entries carry metadata.
        assert_eq!(p1_st03.card_name, "Koromon");
    }

    #[test]
    fn deck_cards_serializes_as_object() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        let v = serde_json::to_value(lg.deck_cards()).unwrap();
        assert!(v["deck1"].is_array());
        assert!(v["deck2"].is_array());
    }

    #[test]
    fn has_recording_false_for_from_decks() {
        let db = minimal_db();
        let lg = LiveGame::from_decks(small_deck(), small_deck(), Some(1), &db).unwrap();
        assert!(!lg.has_recording());
        assert!(lg.recorded_actions(true).is_none());
    }

    #[test]
    fn recorded_actions_for_recording_game_no_labels() {
        let db = minimal_db();
        let mut hr = crate::HeadlessRunner::new(
            small_deck(),
            small_deck(),
            &db,
            false,
            true,
            false,
            Some(11),
        )
        .unwrap();
        hr.step(0);
        hr.step(0);
        hr.step(62);
        let recording = hr.get_recording().unwrap();
        let lg = LiveGame::from_recording(recording, &db).unwrap();
        assert!(lg.has_recording());
        let actions = lg
            .recorded_actions(false)
            .expect("recorded actions present");
        // 2 mulligan + 1 pass = 3 actions.
        assert_eq!(actions.len(), 3);
        // Labels off → all None.
        assert!(actions.iter().all(|a| a.label.is_none()));
    }

    #[test]
    fn recorded_actions_with_labels_decodes_mulligan_and_replay_actions() {
        let db = minimal_db();
        let mut hr = crate::HeadlessRunner::new(
            small_deck(),
            small_deck(),
            &db,
            false,
            true,
            false,
            Some(11),
        )
        .unwrap();
        hr.step(0);
        hr.step(0);
        hr.step(62);
        let recording = hr.get_recording().unwrap();
        let lg = LiveGame::from_recording(recording, &db).unwrap();
        let actions = lg.recorded_actions(true).expect("recorded actions present");
        // First two are mulligan keeps.
        assert!(actions[0].label.as_deref() == Some("mulligan: keep"));
        assert!(actions[1].label.as_deref() == Some("mulligan: keep"));
        // Third is a non-mulligan PASS — label is set (exact text is
        // decoded from the action explainer, so we just assert non-empty).
        assert!(actions[2].label.is_some());
        assert!(!actions[2].label.as_ref().unwrap().is_empty());
    }

    #[test]
    fn from_recording_round_trip() {
        let db = minimal_db();
        // Record a tiny game with HeadlessRunner.
        let mut hr = crate::HeadlessRunner::new(
            small_deck(),
            small_deck(),
            &db,
            false,
            true,
            false,
            Some(99),
        )
        .unwrap();
        hr.step(0); // mull keep
        hr.step(0);
        hr.step(62); // pass
        let recording = hr.get_recording().unwrap();

        let lg = LiveGame::from_recording(recording.clone(), &db).expect("from_recording");
        // Step 0 — pre-replay state but post-mulligan reconstruction.
        // Turn 1 already established; recording's first replayable action
        // hasn't been applied yet.
        assert_eq!(lg.game.turn_count, 1);

        // Step ahead to step 1 and confirm the live game advances past the
        // first recorded post-mulligan action.
        let lg2 =
            LiveGame::from_recording_at_step(recording, 1, &db).expect("from_recording_at_step");
        assert!(lg2.game.turn_count >= 1);
    }
}
