"""Complete trait + card-name lexicons for keyword-gate denoising (Phase 2, task 2.2).

The new-keyword detector is a set-subtraction; its accuracy lives or dies on
lexicon COMPLETENESS. An incomplete trait list lets traits (Aqua, Sea Animal,
Rock, Sovereign, Social/Tool/Game) masquerade as candidate keywords. So both
lexicons are built from the WHOLE card database, never a per-set sample.

In ``cards.json`` the ``type_eng`` field is already a list of trait strings and
``card_name_eng`` is the printed name — so building the lexicons is a flatten.
"""

from __future__ import annotations

import json
import re


def build_trait_lexicon(cards: dict | list) -> set[str]:
    """Every distinct trait (lowercased) across the full card DB."""
    rows = cards.values() if isinstance(cards, dict) else cards
    out: set[str] = set()
    for r in rows:
        traits = r.get("type_eng")
        if isinstance(traits, list):
            for t in traits:
                if t:
                    out.add(str(t).strip().lower())
        elif isinstance(traits, str) and traits.strip():
            # tolerate legacy slash/comma-delimited strings
            import re

            for t in re.split(r"[\/,]", traits):
                if t.strip():
                    out.add(t.strip().lower())
    return out


def build_name_lexicon(cards: dict | list) -> set[str]:
    """Every distinct card name (lowercased) across the full card DB."""
    rows = cards.values() if isinstance(cards, dict) else cards
    out: set[str] = set()
    for r in rows:
        nm = r.get("card_name_eng")
        if nm and str(nm).strip():
            out.add(str(nm).strip().lower())
    return out


# "Sistermon Noir (Awakened)" / "Belphemon: Rage Mode" -> the family stem.
_NAME_STEM_RE = re.compile(r"^(.+?)\s*(?:\(.*\)|:\s.*)$")


def name_stems(names) -> set[str]:
    """Card-family stems of the (lowercased) names that carry a mode suffix.

    Printed text names a family by its stem — BT7-083 places "[Sistermon
    Noir]" while the DB holds only "Sistermon Noir (Awakened)"; "[Belphemon]"
    for "Belphemon: Rage Mode". Derived at read time, never stored: a stem is a
    weaker match than a name and the keyword gate consults it last.
    """
    out: set[str] = set()
    for n in names:
        m = _NAME_STEM_RE.match(n)
        if m:
            stem = m.group(1).strip()
            if stem and stem != n:
                out.add(stem)
    return out


def build_lexicons(cards: dict | list) -> dict:
    return {
        "traits": sorted(build_trait_lexicon(cards)),
        "card_names": sorted(build_name_lexicon(cards)),
    }


def _load_cards() -> dict:
    from data_paths import CARDS_JSON

    with open(CARDS_JSON, encoding="utf-8") as f:
        data = json.load(f)
    return {c["card_id"]: c for c in data} if isinstance(data, list) else data


def write_lexicons(out_path: str = "data/author_set_lexicons.json", cards=None) -> dict:
    if cards is None:
        cards = _load_cards()
    lex = build_lexicons(cards)
    lex["_comment"] = (
        "Generated by tools/author_set/lexicons.py from the full cards.json. "
        "Completeness matters — never build from a per-set sample."
    )
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(lex, f, indent=2, ensure_ascii=False)
    return lex


def load_lexicons(path: str = "data/author_set_lexicons.json") -> tuple[set[str], set[str]]:
    """Return ``(traits, card_names)`` as sets."""
    with open(path, encoding="utf-8") as f:
        lex = json.load(f)
    return set(lex.get("traits", [])), set(lex.get("card_names", []))


if __name__ == "__main__":
    lex = write_lexicons()
    print(f"traits: {len(lex['traits'])}  card_names: {len(lex['card_names'])}")
