"""Tested-cards allowlist for the alpha deck builder.

Loads ``tested_cards.json`` (sibling file, committed to the repo) and
exposes fast membership helpers for the hosted API's deck-tools router.
The snapshot is regenerated by ``tools/build_tested_cards.py`` from
per-card behavioral test files under ``tests/behavioral/``. The desktop
app consumes the same JSON via ``include_str!`` in
``digimon-engine/src/deck_tools.rs``.

This module MUST NOT import from ``digimon_gym.db`` or
``digimon_gym.ai`` so it stays safe to import from engine-only routers.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Iterable

_TESTED_CARDS_PATH = Path(__file__).parent / "tested_cards.json"


@lru_cache(maxsize=1)
def load_tested_cards() -> frozenset[str]:
    """Return the full set of tested card IDs as a frozenset."""
    with _TESTED_CARDS_PATH.open() as f:
        payload = json.load(f)
    return frozenset(payload["card_ids"])


def is_card_tested(card_id: str) -> bool:
    return card_id in load_tested_cards()


def out_of_set_cards(card_ids: Iterable[str]) -> list[str]:
    """Return the distinct card IDs that are NOT in the tested-cards allowlist.

    Order is preserved (first-seen) and duplicates collapsed so callers can
    render one error per offending card even when the deck has multiple
    copies.
    """
    tested = load_tested_cards()
    seen: set[str] = set()
    out: list[str] = []
    for cid in card_ids:
        if cid in tested or cid in seen:
            continue
        seen.add(cid)
        out.append(cid)
    return out
