#!/usr/bin/env python3
"""Generate the bundled 6 starter decks from the deck library.

Reads the 6 `starter_st*` decklists in `data/deck_library.json`, splits each
into egg (card_kind == 3) and main using `data/cards.json`, and emits:
  * data/starter_decks.json                                  (canonical; Rust include_str!)
  * code/frontend/src/features/play/starterDecks.generated.ts (frontend picker source)

Run from anywhere:  python code/tools/gen_starter_decks.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]  # tools -> code -> repo root
DATA = ROOT / "data"

# (deck_id in deck_library.json) -> (set id, display name)
DECKS = [
    ("starter_st1_gaia_red", "ST1", "Starter Deck Gaia Red"),
    ("starter_st2_cocytus_blue", "ST2", "Starter Deck Cocytus Blue"),
    ("starter_st3_heavens_yellow", "ST3", "Starter Deck Heaven's Yellow"),
    ("starter_st4_giga_green", "ST4", "Starter Deck Giga Green"),
    ("starter_st5_machine_black", "ST5", "Starter Deck Machine Black"),
    ("starter_st6_venomous_violet", "ST6", "Starter Deck Venomous Violet"),
]
EGG_KIND = 3  # cards.json card_kind: 0 digimon, 1 tamer, 2 option, 3 digi-egg


def _walk(obj):
    if isinstance(obj, dict):
        if "deck_id" in obj and "decklist" in obj:
            yield obj
        for v in obj.values():
            yield from _walk(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _walk(v)


def main() -> None:
    lib = json.loads((DATA / "deck_library.json").read_text(encoding="utf-8"))
    cards = json.loads((DATA / "cards.json").read_text(encoding="utf-8"))

    found = {}
    wanted = {d[0] for d in DECKS}
    for entry in _walk(lib):
        did = entry["deck_id"]
        if did in wanted and did not in found:
            dl = entry["decklist"]
            found[did] = json.loads(dl) if isinstance(dl, str) else list(dl)

    decks = []
    for did, set_id, name in DECKS:
        if did not in found:
            raise SystemExit(f"starter deck {did!r} not found in deck_library.json")
        dl = found[did]
        egg = [c for c in dl if cards.get(c, {}).get("card_kind") == EGG_KIND]
        main = [c for c in dl if cards.get(c, {}).get("card_kind") != EGG_KIND]
        if len(main) != 50:
            raise SystemExit(f"{did}: expected 50 main cards, got {len(main)}")
        if len(egg) > 5:
            raise SystemExit(f"{did}: egg deck {len(egg)} exceeds 5")
        decks.append(
            {
                "id": did,
                "name": name,
                "set": set_id,
                "game_mode": "starter",
                "egg_deck": egg,
                "main_deck": main,
            }
        )

    out = {
        "version": 2,
        "_generated_by": "code/tools/gen_starter_decks.py",
        "starter_decks": decks,
    }
    (DATA / "starter_decks.json").write_text(
        json.dumps(out, indent=2) + "\n", encoding="utf-8"
    )

    def ts_deck(d):
        return (
            "  {\n"
            f"    id: {json.dumps(d['id'])},\n"
            "    owner_id: 'builtin',\n"
            "    folder_id: null,\n"
            f"    name: {json.dumps(d['name'])},\n"
            f"    description: {json.dumps('Official ' + d['set'] + ' starter deck.')},\n"
            "    game_mode: 'starter',\n"
            f"    main_deck: {json.dumps(d['main_deck'])},\n"
            f"    egg_deck: {json.dumps(d['egg_deck'])},\n"
            "    main_deck_alt_arts: [],\n"
            "    egg_deck_alt_arts: [],\n"
            "    commander_id: null,\n"
            "    is_valid: true,\n"
            "    validation_errors: [],\n"
            "    is_public: false,\n"
            "    is_pinned: false,\n"
            "    tags: ['starter'],\n"
            "    meta_tier: null,\n"
            f"    meta_archetype: {json.dumps(d['set'])},\n"
            "    is_builtin: true,\n"
            "    created_at: '2024-01-01T00:00:00Z',\n"
            "    updated_at: '2024-01-01T00:00:00Z',\n"
            "  }"
        )

    ts = (
        "// @generated by code/tools/gen_starter_decks.py — DO NOT EDIT.\n"
        "import type { DeckResponse } from '@/types/deck';\n\n"
        "export const STARTER_DECKS: DeckResponse[] = [\n"
        + ",\n".join(ts_deck(d) for d in decks)
        + "\n];\n"
    )
    (ROOT / "code/frontend/src/features/play/starterDecks.generated.ts").write_text(
        ts, encoding="utf-8"
    )
    print(f"wrote {len(decks)} starter decks")


if __name__ == "__main__":
    main()
