#!/usr/bin/env python3
"""Queue review_batch tasks from a build_review_batches plan file."""

from __future__ import annotations

import argparse
import json
import os
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


def post_json(
    *,
    url: str,
    token: str,
    payload: dict[str, Any],
) -> dict[str, Any]:
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Queue review_batch tasks from plan JSON")
    parser.add_argument(
        "--plan",
        type=Path,
        default=Path("data/review/six_set_review_plan.json"),
        help="Path to review plan JSON generated by build_review_batches.py",
    )
    parser.add_argument("--base-url", default=os.getenv("DIGIMON_API_BASE_URL", "http://127.0.0.1:8000"))
    parser.add_argument("--token", default=os.getenv("DIGIMON_ADMIN_BEARER_TOKEN", ""))
    parser.add_argument("--task-type", default="review_batch")
    parser.add_argument("--model-name", default="")
    parser.add_argument("--max-tasks", type=int, default=0, help="Optional cap for number of batches to queue")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.plan.exists():
        print(f"Plan file not found: {args.plan}")
        return 1

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    batches = plan.get("batches", [])
    if not isinstance(batches, list) or not batches:
        print("No batches found in plan.")
        return 1

    max_tasks = args.max_tasks if args.max_tasks > 0 else len(batches)
    selected = batches[:max_tasks]
    print(f"Selected {len(selected)} batches from {len(batches)} total")

    if args.dry_run:
        for idx, batch in enumerate(selected, start=1):
            card_ids = [str(card.get("card_id", "")) for card in batch if isinstance(card, dict)]
            print(f"  Batch {idx}: {len(card_ids)} cards ({', '.join(card_ids)})")
        return 0

    if not args.token:
        print("Missing admin bearer token. Pass --token or set DIGIMON_ADMIN_BEARER_TOKEN.")
        return 1

    endpoint = args.base_url.rstrip("/") + "/admin/ai-tasks"
    queued = 0
    for idx, batch in enumerate(selected, start=1):
        payload = {
            "task_type": args.task_type,
            "payload": {"cards": batch},
            "cost_estimate": 0.0,
        }
        if args.model_name:
            payload["model_name"] = args.model_name
        try:
            resp = post_json(url=endpoint, token=args.token, payload=payload)
            print(f"Queued batch {idx}/{len(selected)} -> task_id={resp.get('id')} status={resp.get('status')}")
            queued += 1
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            print(f"Failed batch {idx}/{len(selected)}: HTTP {exc.code} {detail}")
        except Exception as exc:
            print(f"Failed batch {idx}/{len(selected)}: {exc}")

    print(f"Queued {queued}/{len(selected)} tasks")
    return 0 if queued == len(selected) else 1


if __name__ == "__main__":
    raise SystemExit(main())
