"""Admin release management router for Tauri auto-updater.

Writes: /admin/releases/*  (all require ROLE_ADMIN)
The public read surface is the static manifest at
  <SPACES_CDN_URL or endpoint>/updates/<channel>/latest.json
which is regenerated by this module on publish/unpublish.
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timezone

from botocore.exceptions import ClientError
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from digimon_gym.db.auth import ROLE_ADMIN, require_roles
from digimon_gym.db.database import get_db
from digimon_gym.db.models import AppRelease, AppReleaseArtifact, User
from digimon_gym.db.schemas import (
    AppReleaseArtifactUploadSlot,
    AppReleaseConfirmRequest,
    AppReleaseConfirmResponse,
    AppReleaseCreateRequest,
    AppReleaseCreateResponse,
)
from digimon_gym.storage import spaces

admin_router = APIRouter(prefix="/admin/releases", tags=["admin-releases"])

UPLOAD_URL_TTL = 900  # seconds

_PRODUCT_SLUG = "digimon-tcg"
_TARGET_EXTENSION = {
    "windows-x86_64": "x86_64-setup.exe",
    "linux-x86_64": "x86_64.AppImage",
}


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _artifact_filename(version: str, target: str) -> str:
    ext = _TARGET_EXTENSION[target]
    return f"{_PRODUCT_SLUG}-{version}-{ext}"


def _artifact_spaces_key(release_id: str, filename: str) -> str:
    return f"releases/{release_id}/{filename}"


@admin_router.post(
    "",
    response_model=AppReleaseCreateResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_release(
    request: AppReleaseCreateRequest,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseCreateResponse:
    """Create an AppRelease row and return a presigned PUT URL per target."""
    existing = await db.scalar(
        select(AppRelease).where(
            AppRelease.channel == request.channel,
            AppRelease.version == request.version,
        )
    )
    if existing is not None:
        raise HTTPException(
            status_code=409,
            detail=(
                f"release already exists for channel={request.channel} "
                f"version={request.version}"
            ),
        )

    release = AppRelease(
        version=request.version,
        channel=request.channel,
        engine_commit=request.engine_commit,
        min_version=request.min_version,
        release_notes=request.release_notes,
        state="pending",
        published=False,
    )
    db.add(release)
    await db.flush()  # populate release.id via _new_uuid default

    slots: list[AppReleaseArtifactUploadSlot] = []
    for target in request.targets:
        filename = _artifact_filename(request.version, target)
        key = _artifact_spaces_key(release.id, filename)
        artifact = AppReleaseArtifact(
            release_id=release.id,
            target=target,
            spaces_key=key,
            filename=filename,
        )
        db.add(artifact)
        upload_url = await asyncio.to_thread(
            spaces.generate_presigned_put,
            key,
            UPLOAD_URL_TTL,
            "application/octet-stream",
        )
        slots.append(
            AppReleaseArtifactUploadSlot(
                target=target,
                upload_url=upload_url,
                spaces_key=key,
                filename=filename,
                expires_in=UPLOAD_URL_TTL,
            )
        )

    await db.commit()

    return AppReleaseCreateResponse(
        release_id=release.id,
        version=release.version,
        channel=release.channel,
        artifacts=slots,
    )


@admin_router.post(
    "/{release_id}/artifacts/{target}/confirm",
    response_model=AppReleaseConfirmResponse,
)
async def confirm_artifact(
    release_id: str,
    target: str,
    request: AppReleaseConfirmRequest,
    _: User = Depends(require_roles(ROLE_ADMIN)),
    db: AsyncSession = Depends(get_db),
) -> AppReleaseConfirmResponse:
    """Confirm CI upload: HEAD the object, stream SHA-256, store signature."""
    artifact = await db.scalar(
        select(AppReleaseArtifact).where(
            AppReleaseArtifact.release_id == release_id,
            AppReleaseArtifact.target == target,
        )
    )
    if artifact is None:
        raise HTTPException(status_code=404, detail="artifact not found")

    # HEAD first so we 422 cleanly on missing upload rather than crashing
    # inside the streaming hash.
    try:
        await asyncio.to_thread(spaces.head_object, artifact.spaces_key)
    except ClientError as e:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Spaces object {artifact.spaces_key} not present "
                f"(CI upload failed?): {e}"
            ),
        )

    try:
        sha256_hex, total_bytes = await asyncio.to_thread(
            spaces.stream_sha256, artifact.spaces_key
        )
    except ClientError as e:
        raise HTTPException(status_code=422, detail=f"stream_sha256 failed: {e}")

    artifact.file_sha256 = sha256_hex
    artifact.file_size_bytes = total_bytes
    artifact.signature_b64 = request.signature_b64
    await db.commit()

    return AppReleaseConfirmResponse(
        release_id=release_id,
        target=target,
        file_sha256=sha256_hex,
        file_size_bytes=total_bytes,
    )
